### ISSUE TITLE
Manual actions should override 'cannot' conditions

### ISSUE THREAD

**Issue by ystros** [throneteki/throneteki#1104]
* [x] Manually clicking a knelt card that cannot stand should stand it anyway.
* [x] Manually clicking a standing card that cannot kneel should kneel it anyway.
* [x] Dragging a card that cannot be killed into the dead pile should kill it anyway.
* [x] Dragging a card that cannot be discarded into the discard pile should discard it anyway.
* [x] Dragging a card that cannot be returned to hand into the hand should return it anyway.
* [x] Dragging a character into play when Barring the Gates is in effect should work.
* [x] Dragging a character into play when Iron Bank Will Have Its Due or Tris Botley is blocking that card name.

**Comment by DukeTax** [comment]
- Using /power X on a card that cannot gain power should have it gain power anyway.

**Comment by zacchiro** [comment]
> * Dragging a card that cannot be returned to hand into the hand should return it anyway.

is this one the same of #1216 or something else?

**Comment by ystros** [comment]
Separate. This is about effect restrictions preventing certain player actions. #1216 is a bug where drag-and-drop is not implemented at all for non-standard piles (Out of Game, Schemes, Conclave).

**Comment by ystros** [comment]
Another scenario to consider - playing The Iron Bank Will Have Its Due on a character should not prevent the player from manually dragging the character back into play if they want to undo the event.
