### ISSUE TITLE
Log should say which character got the attachment

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#1300]
says "RTT marshals Milk of the Poppy costing 1", but doesn't say on which character.

![1](https://user-images.githubusercontent.com/7605827/29042879-86abf174-7bc1-11e7-852b-8836bb5589cb.png)

**Comment by atkeranov** [comment]
Applies to Nightmares and all other targeted abilities. Currently, you have to ask the opponent about the target of the ability before deciding whether to cancel or not.
Applies to Hear me Roar as well - the log should state which character you are trying to put into play before the opponent can decide whether to cancel or not.

**Comment by mplain** [comment]
This is still unimplemented. Would be very helpful.
