### ISSUE TITLE
Show Agenda information in Current Games page

### ISSUE THREAD

**Issue by atkeranov** [throneteki/throneteki#1340]
This is a feature request.

I can see the requests and responses for the Current Games page and it already contains the agenda information. I am interested in particular House/Agenda combinations and I would like to see them without having to spectate every single game which may or may not be that specific House/Agenda.

Please include the Agenda information in the UI for Current Games page (maybe hover on the house card icon to see the full House/Agenda text implemented via a label attribute or something like that).

**Comment by cryogen** [comment]
It’s already there. What device/screen size are you viewing on?

**Comment by cryogen** [comment]
Ah you mean the agenda in addition to the faction. That row is already pretty maxed out with information, I don’t see it fitting on. (Mouse over is an option but doesn’t work on tablets)

**Comment by atkeranov** [comment]
Hi, I just glanced at the code for GameList.jsx and I do not see player.Agenda being used. I was thinking about something like:

gameRow.push(<span className={ 'hidden-xs col-xs-1 game-icon icon-' + player.faction } title={ player.agenda } />);

I know it is not a perfect solution, but it is still something, and it will not add more icons to the UI.

I am using Chrome on a full HD monitor. Here is a screenshot of what I see:
https://www.screencast.com/t/36V27lj1ae

**Comment by DukeTax** [comment]
Closing this issue as the new games list now shows agenda information.
