### ISSUE TITLE
Mag the Mighty and Saves

### ISSUE THREAD

**Issue by ploog** [throneteki/throneteki#1642]
Currently it appears you are allowed to save a character using a dupe for Mag the Mighty and still force the opponent to kill one.  This appears to be wrong as the pre-then was not fully resolved

Mag the Mighty:  Forced Reaction: After you win a challenge in which Mag the Mighty is participating, choose and kill a character you control. Then, the losing opponent chooses and kills a character he or she controls.

RRG:  Save:  When a card is saved from an effect that attempts to remove that card from play, the card remains in play as the effect resolves and is not considered to have been killed, discarded, or otherwise removed from play by the effect

RRG: Then:If the pre-then aspect of an effect does not successfully resolve in full, the post-then aspect does not attempt to resolve.

http://www.cardgamedb.com/forums/index.php?/topic/37865-risen-from-the-sea-vs-mag-the-mighty/

**Comment by cryogen** [comment]
Thanks for the report. This is not (technically) a bug but more of a limitation in the implementation. The limitation is detailed in the How To Play guide on the site
