### ISSUE TITLE
Simultaneously expiring strength increases and decreases not evaluated correctly with terminal burn

### ISSUE THREAD

**Issue by illurion** [throneteki/throneteki#1706]
There's a couple of cases that I've seen where this causes characters to die to terminal burn effects that shouldn't.

Scenario 1: A 5 str character is in attacking in the first challenge with Lord of the Crossing giving -1 str. The player uses iron fleet scout to increase str by 2. Dracarys is played to take their str to 2. When the challenge ends, iron fleet scout and lord of the crossing should expire simultaneously. Instead, the site removes the +2 str first, sees the character's str is 0, and kills them before removing the -1 from crossing.

Scenario 2: A 5 str character has crown of gold attached. On the next turn, blood of the dragon and a song of summer are revealed, so the character stays alive. In the next round when plots are revealed, both should expire simultaneously and the character should survive. Instead, the site removes the +1 str from a song of summer first, sees the character's str is 0, and kills them before removing the -1 from blood of the dragon.

**Comment by ystros** [comment]
Thanks for the detailed report (and narrowing it down to expiration)!
