### ISSUE TITLE
Could not take control with Daario 

### ISSUE THREAD

**Issue by CcJeannie** [throneteki/throneteki#1809]
After winning a military with Daario Naharis, I was able to choose opponents Grey Worm to take control, and stand him, but it didn't end up on my side of the play area. It stood card and stayed on opponent's side. We resolved the rest of the round manually. This occurred around 1:00AM EST on Friday 3/9/18.

Thank you for all the work you do!

**Comment by DukeTax** [comment]
Thanks for reporting. I haven't been able to reproduce this. It's been a while, but could it have been the case you had a Grey Worm yourself in your dead pile? Aside from that, you could've resolved the switching of control manually by having your opponent use the `/give-control` command and select Grey Worm.

**Comment by zacchiro** [comment]
Closing as this is quite old, unreproducible, and without further info.
@CcJeannie feel free to reopen if you manage to reproduce it again.
