### ISSUE TITLE
False Spring inconsistent implementation 

### ISSUE THREAD

**Issue by Redal59** [throneteki/throneteki#1867]
False Spring has been inconsistent in it's triggering, sometimes it works fine other times (more often when chosen to resolve after another when revealed effect) it is simply skipped. 

It's not a matter of hand size either, potentially to large a hand size is an issue maybe? It's happened a few times when opponent has played counting coppers.

**Comment by ystros** [comment]
Thanks for the report! This sound pretty similar to a bug reported about Valar Dohaeris (#1821), so it may be a general bug with plot reveals. A couple follow ups if you can remember:

1. Have you ever seen it skip False Spring when the first player resolves it first, or only if the other plot is resolved first?
2. Have you noticed that it happens (or happens more) during a particular round? E.g. w/ the Dohaeris bug, it was played on round 3.
3. During a game where it happened, were any unusual plots like The Withering Cold played?

**Comment by Redal59** [comment]
1. Can't say for certain, I believe it happened both on being first plot triggered and second.  It seemed more common when it was chosen second however. 

2. & 3. Apart from the above I haven't noticed any pattern to opponents plots or which round it was played on.  If I learn anymore about it I'll post it here.

**Comment by DukeTax** [comment]
I just had a skipped When Revealed, these were the circumstances:

Martell The Wars To Come mirror match.

- First turn: I reveal At Prince Doran's Behest vs opponent's Varys' Riddle.
- Opponent makes me first player.
- I trigger Riddle first, making my opponent reveal a new plot.
- He uses Riddle to reveal At Prince Doran's Behest. At this point his Behest should immediately trigger for him to reveal a new plot, but it didn't.
- My At Prince Doran's Behest triggers, I reveal Counting Coppers.
- My Coppers triggers and I draw 3 cards.
- Draw phase starts.

So my opponent ended up with At Prince Doran's Behest as his revealed plot for the turn.

This is the relevant part of the game log.

`DukeTax has selected a plot
kawson has selected a plot
kawson won initiative
kawson has selected DukeTax to be the first player
DukeTax has chosen to resolve first the when revealed ability of kawson's Varys's Riddle
kawson uses Varys's Riddle to initiate the When Revealed ability of At Prince Doran's Behest
kawson uses At Prince Doran's Behest to reveal At Prince Doran's Behest
DukeTax uses At Prince Doran's Behest to reveal Varys's Riddle
DukeTax uses Varys's Riddle to initiate the When Revealed ability of At Prince Doran's Behest
DukeTax uses At Prince Doran's Behest to reveal Counting Coppers
DukeTax uses Counting Coppers to draw 3 cards to hand
DukeTax draws 2 cards for the draw phase
kawson draws 2 cards for the draw phase`

**Comment by DukeTax** [comment]
I guess it's not impossible for this to happen if my opponent clicked 'Done' without selecting a plot when he was prompted for his own At Prince Doran's Behest, during step 4, but who knows.

**Comment by ystros** [comment]
Closing this for now, please re-open or open a new issue if you run into plots being skipped again (haven't heard anyone mention it in a while)
