### ISSUE TITLE
High Septon and game log sequence

### ISSUE THREAD

**Issue by ruijiaxu** [throneteki/throneteki#1981]
When an opponent targets a character with a triggered ability while I have the High Septon out, his interrupt ability is being triggered before the game log tells me who is being targeted.  This information is needed to make an informed decision on whether to trigger the High Septon.  Often times I can ask my opponent who they are targeting but sometimes the opponent is non-responsive or we don't speak the same language.  It would be ideal if the game log told me who was being targeted by what first.  Thanks!

**Comment by ystros** [comment]
Thanks for the report!

Adding this info to the game log would require massively reworking how all game messages are output. It may be something we do in the future, but it will require a lot of thought.

In the meantime, I've added the targeting information to the prompt before you decide to trigger High Septon in #1982. It's the same information you get for cancellation prompts like Hand's Judgement or Treachery. It should help make it more clear what's happening before you decide to trigger.

Example:
![screen shot 2018-05-18 at 5 44 58 pm](https://user-images.githubusercontent.com/145077/40263285-d06db7e2-5ac4-11e8-9eb8-e4feed0f14e5.png)
