### ISSUE TITLE
Summons

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#1983]
Hello

I have used Summons and was presented with 3 options to select from 10 cards: Begging brother, Septa Mordane and the Balckfish. I chose Septa, but in the draw phase I revceive High Septon and Great Hall. How is it possible that High Septon was not presented to me? (I had High Septon already in play).

![summons](https://user-images.githubusercontent.com/39171688/40278874-cf32227c-5c41-11e8-927e-79cf7c2d4922.png)

**Comment by zacchiro** [comment]
After the When Revealed ability of Summons is resolved, the deck is shuffled, so the cards you draw in the draw phase have, in general, nothing to do with what you've been offered to add to your hand for Summons.

**Comment by sergselin** [comment]
yes, I should have paid attention, sorry for trouble

**Comment by zacchiro** [comment]
no trouble at all! please report other issues if you encounter them
