### ISSUE TITLE
The Great Sept of Baelor

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#1984]
The Great Sept of Baelor should blank characters until the end of the round, not until end of phase.

![sept](https://user-images.githubusercontent.com/39171688/40278909-5cfd6bb6-5c42-11e8-97ea-3b9a36d9f99d.png)

**Comment by zacchiro** [comment]
Thanks for reporting!
The card implementation is actually correct, but the message in the game log was wrong. Fix is now on the way.
