### ISSUE TITLE
Riverrun

### ISSUE THREAD

**Issue by Contortore** [throneteki/throneteki#1986]
Riverrun did not work

**Comment by zacchiro** [comment]
Thanks for your report!
Still, we can't do much to investigate this issue if you don't give us more information, and possibly a screenshot showing the problem. Riverrun works for many other people, so if really it didn't work for you, it is probably related to a specific condition that occurred in your game.

**Comment by cryogen** [comment]
As above we will need significanlty more information if we're to look into this
