### ISSUE TITLE
Blanking non-character attachments with Brother's Robes

### ISSUE THREAD

**Issue by chordowa** [throneteki/throneteki#2014]
Attachments attached to locations should be discarded as illegally attached after blanking - they don't and I am forced to politely ask my opponent to discard them manually every time I use Robes on them. And as this ruling is rather counter intuitive often explain it to them for some time.

Is it possible to implement that kind of constant state check in those attachments?

**Comment by ystros** [comment]
Thanks for the report!

It does constantly check that attachments are attached to a valid parent, but blanking the attachment wasn't properly reverting location-based attachments to a character-based attachment when blanked. Good catch!
