### ISSUE TITLE
Bolton Flayer is allowing Saves

### ISSUE THREAD

**Issue by fayezm** [throneteki/throneteki#2030]
When a character is killed via Bolton Flayers ability, no saves are allowed

Line 13 in BoltonFlayer.js should be (I think):  
this.game.killCharacter(context.target, { allowSave: false });

(Spent an hour trying to get the dev environment up but gave up in the end, this will need to do instead of a pull request)

**Comment by DukeTax** [comment]
Thanks for reporting. If you're interested in getting the dev environment up and running and/or working on it yourself, you could join our discord: https://discord.gg/A8GUPx
