### ISSUE TITLE
Arianne Martell (Core) + reactions to entering play

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2053]
When Arianne puts a character into play, any reactions to that character entering play should trigger after Arianne returns to hand (e.g. Ramsay Snow, Areo Hotah, Hotah's Axe).

**Comment by ystros** [comment]
Thanks! This is similar to the problem with Mag the Mighty (#1642) in that we don't have proper support for "Then" effects. Getting fairly close now, but not quite there yet.
