### ISSUE TITLE
 You must verifiy your account before trying to log in

### ISSUE THREAD

**Issue by dondrogo** [throneteki/throneteki#2065]
I have no idea how to verify my account, i have check your website in every section and don't how to get rid of this.

Thanks for helping me to acces again to this great website !

**Comment by cryogen** [comment]
What's your username on the site? :)

**Comment by Razgriz85** [comment]
same problem: razgriz85

**Comment by dondrogo** [comment]
don drogo

**Comment by dondrogo** [comment]
same for my girlfriend with username lady oleananas !

**Comment by cryogen** [comment]
Huh.  I can't find any of those accounts.  Did you register with a mixture of upper case and lowercase letters?

**Comment by Razgriz85** [comment]
Razgriz85 to be exact

**Comment by dondrogo** [comment]
don_drogo sorry

**Comment by cryogen** [comment]
Fixed in 3c0a7522873fd328fb566514c7a4c9c294598dfa - should work now, apologies!

**Comment by dondrogo** [comment]
thank u ! see ya in a game !

**Comment by Kilroy88** [comment]
Hello!

Still same problem...

**Comment by Atomknigth** [comment]
Hello, I have the same problem, my account is atomknigth

**Comment by cryogen** [comment]
Done
