### ISSUE TITLE
dragonglass dagger and astapor

### ISSUE THREAD

**Issue by SerMone** [throneteki/throneteki#2073]
A night's watch character with dragonglass dagger is participating in a challenge and the targaryen opponent use astapor (2 golds or more) and another burn event to that character. the strenght of the character is still greater than zero so he doesn't die and everything is going well. at the end of the challenge the lasting effects of dragon glass dagger and astapor end and the character should be alright but he dies.
apparently the lasting effect of the dragon glass dagger ends earlyer than astapor but this should not happen.
thank you for the attention

**Comment by zacchiro** [comment]
Known issue (#1706), but thanks anyway for reporting an additional occurrence!
