### ISSUE TITLE
Issue with verifying email address

### ISSUE THREAD

**Issue by Gj999** [throneteki/throneteki#2086]
Hi, 

I am having some trouble verifying my account. I everytime i try to login it asks me to verify and when i use the link in the email it takes me back to the login page with no change.

my Username is ShadowTower. 

Thanks

**Comment by fcavallaro** [comment]
Hi, same problem here, my Username is Glorfindel

**Comment by fcavallaro** [comment]
Hi, same problem here, I play since 3 months and it now asks me to verify. If I click on the old verification e-mail it gives me an error. My username is Glorfindel

Thanks

**Comment by cryogen** [comment]
Apologies for not getting back to you sooner.  This should have been fixed a long time ago, please reopen if this is still an issue in any way.
