### ISSUE TITLE
Banner cards hidden

### ISSUE THREAD

**Issue by IMABUNNEH** [throneteki/throneteki#2088]
![image](https://user-images.githubusercontent.com/29951413/42379720-8c90ec76-8123-11e8-9550-d9e811540a00.png)

Can't open banner cards window without it opening down. On Chrome, tried different settings, and zooming in and out to different degrees.

Less of an issue if Qohor gets an automated prompt? Still probably necessary to open them upwards for the player not downwards.

**Comment by DukeTax** [comment]
All the popup screens should be draggable. Did you try that?

**Comment by ystros** [comment]
As mentioned, you should be able to drag the popup so that it is visible. But there's a fix coming for its default position. Thanks for the report!

**Comment by IMABUNNEH** [comment]
I did try dragging it and was unable to. It didn't act like an interactive element at all.
