### ISSUE TITLE
Trading with Qohor doesn't work in Alliance

### ISSUE THREAD

**Issue by Stephen986** [throneteki/throneteki#2094]
The game doesn't ask you to trigger Qohor, nor is there any way to manually trigger it, when using Qohor in an Alliance deck.  An example deck: https://thronesdb.com/decklist/view/11547/the-fury-of-the-babies-winner-vignola-regional-1.0

**Comment by cryogen** [comment]
Duplicate of #2805. Thanks for reporting!
