### ISSUE TITLE
Sansa Stark (WotN) with The Wall (tMoW)

### ISSUE THREAD

**Issue by redsquadronk** [throneteki/throneteki#2097]
Played a game last night where I used the new 6-cost version of The Wall to steal a copy of 2-cost Sansa Stark from my opponent's discard pile. Once Sansa was in play, the game set her STR to 0, even though I had no Stark characters in my dead pile. My opponent did have a lot of Stark characters in their dead pile, so I'm guessing it was still referencing their dead pile despite my control of the character.

**Comment by redsquadronk** [comment]
In the game where it happened we were pretty deep in, so I had a bunch of
NW characters in my dead pile. Maybe she counted those as Stark? I believe
we were both playing mono-faction, so there were no strength reduction
cards in play.

I think I had one other slight bug with a character taken via the 6-cost
Wall, but unfortunately I don't remember what it was.

Thanks so much,
   Neil

**Comment by ystros** [comment]
Closing this for now, as we were never able to reproduce it and it's been open for a while. Please re-open or open a new issue if you see this again, or a similar problem!
