### ISSUE TITLE
Sand Steed timing

### ISSUE THREAD

**Issue by joeperson** [throneteki/throneteki#2125]
Sand Steed power should trigger after when revealed effects have been resolved. 

Currently creating some odd situations such as being able to trigger when opponent is revealing king in the north, or letting someone trigger and win a game before a valar morghulis, when actually the characters should die first.

**Comment by mplain** [comment]
Got a ruling for this: http://www.cardgamedb.com/forums/index.php?/topic/39947-ruling-sand-steed-timing/
