### ISSUE TITLE
Harrenhal (white) + Aegon Targaryen

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2129]
I have Harrenhal (white) in play, opponent is first player, brings Aegon Targaryen from shadows, triggers him to put Second Sons into play, now I am prompted to trigger Harrenhal, I click on it, Second Sons is killed, no option to kill Aegon is given at any point.

I should be able to choose between the two characters to kill. If you cannot implement that (because technically it doesn't target), then perhaps it should ask whether I want to kill Aegon, then Second Sons, or opposite order.

![1](https://user-images.githubusercontent.com/7605827/43169477-e8007380-8fa9-11e8-80f9-6f4d3bf0100a.png)

**Comment by DukeTax** [comment]
I haven't tested it, but looking at the screen nothing weird is going on.

- Aegon controller is FP.
- Has first option to trigger reactions to Aegon entering play, triggers Aegon to put Sons into play.
-- Sons enter play.
-- You are prompted to use Harrenhal to kill Sons.

If you pass here, then:

- You are prompted to kill Aegon.

I guess the prompt should clarify which character is triggering Harrenhal at any moment.
