### ISSUE TITLE
Bug for new Doran Martell (7 cost)

### ISSUE THREAD

**Issue by gunslinger83** [throneteki/throneteki#2143]
The wrong ability triggers as a response to losing a challenge. When a challenge is lost, it triggers the "kickout" ability (which is just a normal challenge action). The "real" card response that is an icon stripping effect does not trigger or work at all.

**Comment by gunslinger83** [comment]
Wow...thanks. I did not realize that selecting the card triggers the
response. I thought that this would only exhaust the card. If that works,
that I guess it's not a bug and my bad.

I apologize. Excellent response and response time by the way! You're a
hero!.

**Comment by ystros** [comment]
No problem, I can see how it could be confusing!
