### ISSUE TITLE
[Feature request] Drag'n'droping a character with a dupe

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2166]
Happened a couple of times:
Opponent wins a military challenge. I accidentally click "cancel claim" when prompted to kill a character (or my opponent clicks it). I now have to manually kill a char. I do what comes naturally - drag the char i want to kill from play to the dead pile. Except, i didn't really want to kill that char, I meant to save it with a dupe. But throneteki didn't know that, so that char is now in the dead pile, and its dupes and attachments are in the discard pile.

But-but, drag-n-dropping felt natural...

**Comment by cryogen** [comment]
There is an undocumented /kill command which will resolve this.  Dragging shouldn't always obey the full game flow, especially in cases where you're trying to work around potential bugs or issues.  I'll close this and document the command in the help page
