### ISSUE TITLE
Jamie Lanni after Valyrian's Crew

### ISSUE THREAD

**Issue by peejieweejie** [throneteki/throneteki#2170]
I marshaled core Jamie with Val's crew. The rest of the game he knelt on mil attacks and did not gain renown. Easily fixed with commands and manually, but wanted to report anyway.

**Comment by ystros** [comment]
Thanks! Have you happened to play other take-control-oriented decks (e.g. Stark w/ Ward, various Night's Watch cards, etc) in the past and seen similar bugs? I'm wondering if it's just a bug with take control and not specific to Valyrian's Crew.

**Comment by peejieweejie** [comment]
I only play Bara decks, so I have no other experience with control. It's possible.
