### ISSUE TITLE
Marshaling into Shadows with Val's crew

### ISSUE THREAD

**Issue by peejieweejie** [throneteki/throneteki#2178]
I marshaled a Val's crew facedown Robert Strong into shadows and he went into the other person's shadows instead of mine.

**Comment by ystros** [comment]
Thanks! Though it's not quite intuitive, this is actually the correct behavior. 

Per the rules for the Shadow keyword, the shadows area is considered an out-of-play area. Cards that go to out-of-play areas always end up in the owner's area per the rules guide. So just as returning a controlled card to hand would return to the opponent's hand not yours, marshaling or putting a controlled card into shadows will put in in the opponent's shadow area.

See the answer to this related question about Hagen's Daughter + take control: http://www.cardgamedb.com/forums/index.php?/topic/39882-shadows-take-control-out-of-play-rules/

Normally I'd say it might be useful not to allow players to attempt to marshal a controlled card into shadows. However, there are a few reasons you might want to do it. If you bannered with Targaryen, you could use [Hired Assassin](https://thronesdb.com/card/11053) to immediately kill that character. There's also the upcoming Baratheon character [Red Ronnet](https://thronesdb.com/card/11107) that raises claim while your opponent has a card in shadow, so it may be worth the risk to marshal the card there yourself. Somewhat niche situations but given these and other potential "when your opponent has cards in shadow" cards that may come, I think reason enough to allow it.

**Comment by peejieweejie** [comment]
Thanks! You'd think after years of playing this game I would know that, but I've never been able to marshal something into shadows that wasn't mind before.
