### ISSUE TITLE
[Feature request] Filter to hide ongoing games.

### ISSUE THREAD

**Issue by DrThyme** [throneteki/throneteki#2198]
The new filters for games is quite handy however one problem that I have found is that when I'm looking for both casual and competitive games is that scrolling through all the ongoing casual games to see if there are any competitive games is slightly annoying. Sure one could simple select-deselect the current boxes in order to avoid scrolling but that also seems a bit cumbersome.

A nice feature would be to have another filter checkbox that hides any ongoing games so the only thing that I see are games that are looking for players, sometimes you just wanna play and not watch. :)

**Comment by cryogen** [comment]
This is done and now live
