### ISSUE TITLE
Nagga's Ribs timing

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2203]
Valar Morghulis killed two of my chars, and I saved the third one by a dupe.
Nagga's Ribs prompted, and I placed the discarded dupe into the dead pile. THEN the two killed chars went there, on top of the dupe.
Should work like this: dupe is discarded and chars are placed into the dead pile simultaneously, THEN Nagga moves the dupe to the dead pile. So that the dupe should be the top card.
Very relevant for Old Wyk and Ghosts of Harrenhal in my deck.

**Comment by zacchiro** [comment]
Unless I'm missing something, the timing currently implemented by Throneteki is the correct one, not the one you suggest.

Discarding a dupe is an interrupt to save the character, which triggers before the death of the characters. Nagga's Ribs reaction activates as soon as you place the dupe in your discard pile and, as such, it happens before characters' death too.

**Comment by mplain** [comment]
Huh. It's an interrupt indeed, so they do not enter piles simultaneously... You're right!
