### ISSUE TITLE
Mhysa doesn't add strength

### ISSUE THREAD

**Issue by Neoptolemos** [throneteki/throneteki#2205]
Hey,
Mhysa works only partially - attacking Lady doesn't kneel, but her strength isn't buffed.

**Comment by DukeTax** [comment]
Thanks for the report. A fix should go live soon. In the meantime you can manually correct the parent's strength by using the "/str X" command, with X being the total correct strength.

**Comment by Neoptolemos** [comment]
I use command or just solve it other way, but thanks for fixing :) it's especially important with 4cost Margaery, when there are a lot of modifiers.
