### ISSUE TITLE
Arya Stark (Core) vs Weapons at the Door

### ISSUE THREAD

**Issue by ystros** [throneteki/throneteki#2208]
## Bug
If [Arya Stark (Core)](https://thronesdb.com/card/01141) receives an attachment as the facedown duplicate from her ability, it will be inappropriately be returned to hand by [Weapons at the Door](https://thronesdb.com/card/03051).

## Correct behavior
Because the dupe under Arya is facedown, it should not be considered to have a printed type, and thus not be returned by Weapons at the Door. 

More generally, any ability that relies on a printed characteristic (type, cost, strength, etc) should ignore the facedown duplicate. Only abilities that specifically affect duplicates should work (e.g. [Battle of the Blackwater](https://thronesdb.com/card/04120)).

**Comment by EvadLhorg** [comment]
I think this is fixed by #3135 changing the targeting of weapons at the door to exclude facedown cards
