### ISSUE TITLE
Warded Character with Duplicate Died

### ISSUE THREAD

**Issue by redsquadronk** [throneteki/throneteki#2214]
I duplicated my Septon Celledor on setup. Turn 1 my opponent attached Ward and took control of him. There were no Military challenges, so he had the duplicate into the 2nd round. When my opponent played Valar Morghulis 2nd round, Celledor died despite having a duplicate.

Per this thread (http://www.cardgamedb.com/forums/index.php?/topic/28627-taking-control-and-duplicates/) the owner of the card still controls the duplicates, so I should've been able to save him (and then return him to my control when I Confiscated the Ward).

**Comment by cryogen** [comment]
It should prompt already in that scenario without the option being turned on. So either this is broken or something else is going on
