### ISSUE TITLE
Dacey Mormont + The Wall (TMoW)

### ISSUE THREAD

**Issue by dokempf** [throneteki/throneteki#2216]
This is a glitch rather than a bug: I stole Dacey Mormont with the Wall, which means she is STR0 because of the Walls constant ability to remove affiliations. The game DID implement that, but it did not show the S0 icon on the character, which was confusing, because I immediately thought the implementation to be bugged. To make things even more complicated, it DID show it for my opponent. Maybe related to #2097, which could not be reproduced?

**Comment by mplain** [comment]
Dacey's default STR is 0, she should never show "S0".

**Comment by dokempf** [comment]
That is so true. I feel embarassed. I wonder why my opponent said it would read S0 for him. Still, I would support that strength X characters should always display their actual STR. Not worth an issue though, closing.

**Comment by ystros** [comment]
To confirm, the current behavior is STR only displays if it different from the **numerical value** of the printed STR. For X values, that's always 0. So a Stark-less Dacey would not display STR under the current implementation.

I'd be open to explicitly displaying the STR for X STR characters (just Dacey and Berric at the moment). I can see how that might be confusing.

Doesn't explain your opponent seeing something different, though.
