### ISSUE TITLE
The Free Folk - log displays the opponent's avatar

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2226]
When the extra claim from The Free Folk agenda is applied, the opponent's avatar is displayed in the log window, which normally only happens when the opponent writes something in the chat. Slightly confusing.

![screenshot_15](https://user-images.githubusercontent.com/7605827/45931045-8ac1d000-bf70-11e8-85e7-d6cb0a425821.png)

**Comment by ystros** [comment]
Bizarre. Thanks for the report!
