### ISSUE TITLE
Waiting for Server Issue on Chrome on Mac OS Sierra 10.12.6

### ISSUE THREAD

**Issue by slevin38** [throneteki/throneteki#2227]
I am receiving waiting for server that never goes away when I start a game on Google Chrome on Mac OS Sierra 10.12.6.  I tried clearing cache / cookies.  

Site seems to work fine on Firefox on the same OS.

**Comment by ystros** [comment]
Thanks for the report, and apologies for the late respnose! It seems likely this was a temporary server issue. If you're still having issues, please feel free to re-open the issue.
