### ISSUE TITLE
Attachments discarded due to being illegally attached should show up in the log

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2242]
If something happens that causes an attachment to be discarded due to it being illegally attached, this should show up in the log, so that in can be tracked.

For example, here my opponent marshals Shaggydog (the attachment, "Stark character only") on Septa, and then plays I Am No One at her, making the attachment fall off, but the log doesn't register that.

![screenshot_54](https://user-images.githubusercontent.com/7605827/46299413-f37cfe00-c5a9-11e8-87e1-78e50421b0ba.png)

**Comment by ystros** [comment]
Thanks! I could have sworn we had a message for this already.
