### ISSUE TITLE
 The PLOT "The King in the North"  does not allow a character to be saved by discarding duplicate

### ISSUE THREAD

**Issue by MarioPerotto** [throneteki/throneteki#2245]
Saving a character is a duplicate trigger ability, not a character trigger ability.
I think it's correct to save character by discarding duplicate also with the plot "The King in The North".

**Comment by ystros** [comment]
Thanks for the report! This was already fixed by #2204, but it may not be live on the site. The bug should only be present if you've turned on the "Prompt before using dupes to save" option in your profile.

**Comment by ystros** [comment]
The fix should be live on the server, please re-open with more details (screenshot when it happens helps!) if it occurs again!
