### ISSUE TITLE
[FeatureRequest] Show Competitive games at the top

### ISSUE THREAD

**Issue by ZbignevM** [throneteki/throneteki#2274]
Since the grouping addition, the time to find a competitive game has risen significantly. I guess that this is due to competitive games being at the bottom and usually having a lot of casual games to scroll through.

Simply moving Competitive group over Casual, would hopefully alleviate this issue and make it easier to get those competitive games.

**Comment by mplain** [comment]
I'm not sure this is a good idea. People tend to not read the game name or level, they often just click the first available open game. Bringing competitive games up to top will just make it more common for casual players to join competitive games.

**Comment by cryogen** [comment]
Ticking the "show only open games" would seem to solve both of your problems

**Comment by ZbignevM** [comment]
The problem is that it would require others to press that so that they see my game and based on the increase in waiting time, I assume that nobody uses that option.

Nowadays everyone just creates casual games, because creating a Competitive is a huge bother where often it takes up to 20 minutes before anyone connects.
