### ISSUE TITLE
Flea Bottom puts a duplicate into play, then the wrong dupe is auto-used to save

### ISSUE THREAD

**Issue by mplain** [throneteki/throneteki#2276]
A duped character is in play, and Flea Bottom another duplicate on that character. Later, a duplicate is sacrificed to save the character from military claim. At the end of the phase, the second dupe goes to the bottom of the deck. It would be more sense to discard for mil claim the one dupe put into play by Flea Bottom.

![screenshot_30](https://user-images.githubusercontent.com/7605827/46811869-41e58600-cd7c-11e8-9e54-fb1a2ed1d8c8.png)

**Comment by DukeTax** [comment]
There is a profile option for manual dupes to deal with these cases. It could still make sense the prioritize "FB-dupes" for people who don't want to use that option, but it seems, to me at least, like a lot of work for  relatively little gain.

**Comment by mplain** [comment]
But what is the current automatic choice of the dupe to save? Oldest first? Can you just change it to most recent dupe first?

**Comment by cryogen** [comment]
As Duke says, if you want to control your dupe use, turn on manual dupes.  Changing the default now is only going to upset people who depend on it working that way.

**Comment by mplain** [comment]
o_O What people? Are there any other interactions where the order of dupes discarded is relevant? o_O
