### ISSUE TITLE
"At end of phase" return effects should affect dupes where appropriate

### ISSUE THREAD

**Issue by ystros** [throneteki/throneteki#2277]
## Bug
If a unique character is duplicated via cards like [I Never Bet Against My Family](https://thronesdb.com/card/02050), the "at the end of phase" delayed effect does not currently discard the dupe from play.

## Correct behavior
When the card text says the "card" should be discarded / returned to hand / moved to the bottom of the deck / etc, it should do so even if the card entering play was a dupe.

This is correctly implemented for Flea Bottom, the other similar effects need to be updated.

Note that if it says the "character" should be discarded / etc, (as with [Harrenhal](https://thronesdb.com/card/04050)), then the dupe should not leave play.

[List of potential cards affected](https://thronesdb.com/find?q=x%3A%22into+play%22+x%3A%22at+the+end+of+the+phase%22&sort=set&view=card)

**Comment by EvadLhorg** [comment]
I think this is now fixed with #3135
