### ISSUE TITLE
Doran Martell (Sands of Dorne) - give icon to opponent / remove icons from controlled

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2290]
Doran Martell's abillity allows you to add and remove icons from any character, currently, you can't remove icons from your own characters nor add some to your opponnent's characters.

**Comment by ystros** [comment]
Thanks! Similar to #2141, the card is intentionally implemented in a way that doesn't match the exact text of the ability. I would think in most cases, you want to add icons to your own characters, and remove them from opponent characters. There are always edge cases though.

Could you describe the interactions where you've wanted to have an opponent character gain an icon, or remove an icon from your own character?

**Comment by Patane97** [comment]
> Could you describe the interactions where you've wanted to have an opponent character gain an icon, or remove an icon from your own character?

I see a reason to do these negative-looking effects with the new "Owen the Oaf" NW character:
"While Owen the Oaf is participating in a challenge, each character with more than 1 challenge icon does not contribute its STR to the challenge."
