### ISSUE TITLE
Rickon cancell

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2291]
Rickon's ability allows you to cancel any effect (including your own) with the word "search" currently you can cancel only opponent's ability.

**Comment by ystros** [comment]
Thanks! This is an exact duplicate of issue #2141. 

It might be helpful if you add a comment on that issue describing your reasoning for wanting to cancel your own searches. I suspect it's just to get the extra sacrifice trigger off Rickon, but any additional info on your reason could be helpful on how to prioritize us changing the current behavior.

**Comment by zacchiro** [comment]
@ystros: I've just done so in that issue, as I agree times have changed, and this is now particularly useful with Qohor + sacrifice shenanigans.
