### ISSUE TITLE
Gold Cloaks trigger

### ISSUE THREAD

**Issue by chordowa** [throneteki/throneteki#2321]
I notice recently that that Forced Interrupt of Gold Cloaks trigger wrongly at each end of phase since they enter play by ambush, not only end of particular phase they used ambush. So if you ambush Gold Cloaks on Fortified Positions turn they will get discarded at the end of next plot phase and if you cancel their Forced Reaction with Treachery or Begging Brother, they will get discarded at the end of dominance phase.

This surprises me as I am almost sure they worked properly ~year ago when I last time used them in deck.

**Comment by ystros** [comment]
Thanks for the report! Based on the implementation for Gold Cloaks, it looks like this bug has been present from nearly the beginning of the site. I'm not sure it ever worked properly. Good find!
