### ISSUE TITLE
Crown of Golden Roses

### ISSUE THREAD

**Issue by jodahae** [throneteki/throneteki#2325]
Crown of Golden Roses appears to be remembering and reapplying STR boost when played onto a secondary character after the first has left play.

I.E. I sacrifice Garlan Tyrell to To The Rose Banner, after having used the crown to pump two times, giving him a strength of 7. I then remarshall a second copy of Garlan and reattach the crown and it sets his base STR to 10.

**Comment by ystros** [comment]
Thanks for the report! It looks like this bug was specific to both Crown of Golden Roses and Heartsbane.
