### ISSUE TITLE
Until end of Phase (Dracarys vs Lord Rendy's Ride)

### ISSUE THREAD

**Issue by Sinoples** [throneteki/throneteki#2328]
I think i found a bug, i have a character with 2 STR : 
 1. I use Lord Rendy's Ride to get +3 STR 
 2. My opponent use Dracarys to get -4 STR 

And of phase my character dies. 

There is no resolution sequence when multiple cards use "Until the end of phase". 
So my character should not die.

Regards,

**Comment by ystros** [comment]
Thanks for the report! I honestly thought we already covered this case, but it seems not. I'm surprised it hasn't come up more.
