### ISSUE TITLE
Vindictive Ranger

### ISSUE THREAD

**Issue by Redal59** [throneteki/throneteki#2366]
Every time I've tried to use the triggered reaction on them it ends up giving the chosen to icon all NW characters you control and crashes the game.

**Comment by Stephen986** [comment]
I'm still getting this issue whenever I trigger vindictive ranger on Iron Throne.  It adds the icon to everyone and gives me a server error... the only way to continue the game is to type /cancel-prompt each and every phase of the game.

**Comment by cryogen** [comment]
The fix was not deployed.  It is now :)
