### ISSUE TITLE
Cards that are put into shadows with Assault from the Shadows no longer work

### ISSUE THREAD

**Issue by Odrl7** [throneteki/throneteki#2382]
There seems to be a problem with the cards that do not have the printed shadow keyword, when they are put into shadows with the Assault from the Shadows agenda. You can no longer put them into play by clicking on them, nor do you get prompted to play events (such as The Hand's Judgement) when their triggering condition is met.

I'm sure this all worked correctly in the past, so it seems like it's a recent problem.

**Comment by ystros** [comment]
Thanks for the report! This is definitely not working properly anymore. Likely caused by a bug introduced by #2361.
