### ISSUE TITLE
Wyman's dup triggered him

### ISSUE THREAD

**Issue by SteliosCh21** [throneteki/throneteki#2385]
In a game where I had Wyman dupped and no other character on the board, after a VM he was highlighted/triggered from the removal of his dup.

**Comment by SteliosCh21** [comment]
Unfortunately I didn't capture an image. I revealed VM, I had only Wyman on the board, with one dup and standing. After I chose him and the dup saved him, he was highlighted and I drew a card as usual. If I come upon this again I'll make sure to capture it.
________________________________
Από: Brian Upton <notifications@github.com>
Στάλθηκε: Τετάρτη, 9 Ιανουαρίου 2019 5:26 μμ
Προς: throneteki/throneteki
Κοιν.: SteliosCh21; Author
Θέμα: Re: [throneteki/throneteki] Wyman's dup triggered him (#2385)


Thanks for the report! Could you go into more detail on what happened or do you have a screenshot? Valar Morghulis was revealed, you saved Wyman with his dupe, and then it prompted to trigger Wyman's ability? You're sure you didn't control any other characters that died at the time? Was Wyman standing or kneeling at the time?

**Comment by ystros** [comment]
Thanks! I've actually been able to reproduce this. Very odd.
