### ISSUE TITLE
Valyrian's Crew with events

### ISSUE THREAD

**Issue by chordowa** [throneteki/throneteki#2409]
Events seem to carry all checks and conditions from owner instead of controller while played from under [Valyrian's Crew](https://thronesdb.com/card/11047)

Here is what happened: I played  ["Lord Renly's Ride"](https://thronesdb.com/card/06024) attached to my [Valyrian's Crew](https://thronesdb.com/card/11047) during military challenge with 3 tokens on [Sea of Blood](https://thronesdb.com/card/12045).
Not only I paid 1 gold for it, but also STR bonus was based on opponent's top dead character (+2 from Right instead +5 from City Watch).

So it seams that for the purpose of discounts as well as in-text conditions game treated LRR as played by my opponent.

**Comment by belazhul** [comment]
Verified, I played secret schemes with valyrian crew and the opponent drew the cards
