### ISSUE TITLE
Duel Allows to kneel an already kneeling character

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2412]
Duel text says : "Choose an opponent. That player chooses 2 non-Army characters, each with printed cost 6 or higher. Then, that player chooses and kneels 1 of those characters. Kill the other (cannot be saved)."

the rulling have been confirmed as such : 
"After the two initial target characters are chosen, you must "choose and kneel" one that can be knelt (**you cannot choose a kneeling character**, or Ygritte). Whether the other can be killed or not is irrelevant at this point. If you cannot "choose and kneel" one character, then there is no "other" character to kill, so the remainder of the effect will do nothing."

The card in the soft is currently not working as such, it allows to kneel an already kneeling character, therefore killing the other, while you should not have the choice.

**Comment by ystros** [comment]
Thanks! We weren't checking either kneel state or immunity.
