### ISSUE TITLE
Privileged Position is not working

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2413]
Privileged Position text reads : "Play only if you have not lost a challenge **this round**."

Currently if you've lost a power challenge in the past round you can't play the card untill a new challenge phase accured, wich is not how it should work.

**Comment by ystros** [comment]
Thanks for the report! I can confirm that the check isn't properly reseting at the start of each round. This may require revising how we track challenges in general, as everything is geared towards tracking per phase and there are likely similar bugs.
