### ISSUE TITLE
Maester Murenmure doesn't trigger, when location I own is triggered by opponent

### ISSUE THREAD

**Issue by Martozar** [throneteki/throneteki#2418]
In mirror match-up, I had Murenmure in play, and he stole my Iron Mines. On Valar, he used IM to save a character and Murenmure wasn't triggered to cancel its effect. On the other hand, when I stole his Sea Bitch and tried to use it, I was prompted to cancel its effect with Murenmure, which doesn't happen, when I trigger location I own and control.

**Comment by ystros** [comment]
Thanks! Interactions with take-control are hard to get right. Let us know if you run into other problems like this.
