### ISSUE TITLE
Gift for the Widow for 0 cost doesn't work and makes the game bug

### ISSUE THREAD

**Issue by Laplante1** [throneteki/throneteki#2419]
When you use Gift for the Widow for 0 gold, the soft won't allow you to look for a 0 cost attachement and then the soft won't give you gold during marshall, neither manually and won't count your str for dominance for the rest of the game (it happened several times to me lately).

**Comment by ystros** [comment]
Thanks for the report! Offhand, I can't reproduce this - selecting "0" when prompted for cost for Gift for the Widow searched for 0 cost attachments, put it into play properly, and dominance / collecting income afterwards continued to work properly.

Have you noticed whether it happens every time, or only after certain other things happen first? Does your deck have any cards that modify income or collect gold?

**Comment by Laplante1** [comment]
That's exactly what i meant, can't search for 0 neither, so to be able to play I do it manually.

And yes, I got cards that modify income and collect golds : Roseroad, Minner's Pick and Underground Vault.
The 0 cost attachment i tried to fetch was "Sworn to the Watch".

I haven't done precise test on this bug, all I know is that everytime I try this I end up not collecting gold and not counting str for dom.

**Comment by ystros** [comment]
Are you trying to play Gifts for the Widow while you have 0 gold? I think that may be the bug - I played it while at 0 gold, didn't get the prompt for the X value, got prompted to find a card but wasn't able to select one, and afterwords my gold remained stuck at 0. Whereas it worked fine if I had gold but chose the 0 gold option.

**Comment by Laplante1** [comment]
Yes I was doing this, like I’m supposed to be able (in draw phase to avoid
giving my opponent a gold for Qohor for instance, or before tax to avoid
some card disadvantage).

Le mar. 26 févr. 2019 à 15:53, Brian Upton <notifications@github.com> a
écrit :

**Comment by ystros** [comment]
Thanks! That's definitely how the bug is being triggered. Fix is on the way.
