### ISSUE TITLE
Sacrificing Dreadfort Maester while under Balon (KotI) control doesn't raise the claim of the challenge. 

### ISSUE THREAD

**Issue by renasissianceman6** [throneteki/throneteki#2432]
Had a game last night where I used him a couple times and he didn't raise the claim. Unless there's a rule I am unaware of. I am kinda new.

**Comment by hollandgh** [comment]
+1 I sacrificed him to raise the claim on an intrigue challenge and it didn't raise the claim. Only unusual circumstance in my case was he was under my control having taken him from the other player's discard pile using Old Bear Mormont--not sure if that factors into the bug.

**Comment by EvadLhorg** [comment]
already fixed with https://github.com/throneteki/throneteki/commit/ec5a8abbac87dbf6bcbbfe8e929f72c110acc744

**Comment by renasissianceman6** [comment]
Who even cares anymore?  LMAO
