### ISSUE TITLE
Brother's Robes should not blank Risen from the sea

### ISSUE THREAD

**Issue by Martozar** [throneteki/throneteki#2433]
When you use Brother's robe to blank attached Risen from the sea, it should not blank it's text (so, it should still gain +1 STR) since attachment type, +1 STR and condition trait is gained via Lasting effect of the event and Brother's robe blanks printed text on the attachment and Rissen in attachment form does not have any printed text.

**Comment by ystros** [comment]
Thanks for the report! Is there a ruling to this effect? I agree by the wording of Brother's Robes, it probably should only blank printed text and not gained text (Risen, Blood Magic Ritual, Mare in Heat). But it also seems somewhat against the spirit of Brother's Robe.

**Comment by Martozar** [comment]
It was discussed here and I'm sure it's how it should work 

https://www.facebook.com/groups/agot2ndedition/permalink/2314341365245355/
