### ISSUE TITLE
Mace Tyrell (SAT) doesn't trigger, when is knelt by Duel 

### ISSUE THREAD

**Issue by Martozar** [throneteki/throneteki#2434]

**Comment by ystros** [comment]
Thanks for the report! I haven't been able to reproduce this. Choosing Mace to be knelt via Duel prompted to trigger him properly:

![Screen Shot 2019-03-11 at 7 31 30 PM](https://user-images.githubusercontent.com/145077/54170553-63829080-4434-11e9-9659-de832a350f88.png)

There's nothing special about the way the kneel in Duel works. This feels like either a case of lag (you accidentally clicked past the prompt) or another ability would have prevented Mace from triggering (Fortified Position, King in the North). Have you seen this multiple times / other situations where Mace didn't trigger?

**Comment by Martozar** [comment]
Unfortunately, I wouldnt able to reproduce this bug either, so probably it was a lag. Sorry for false alarm :)
