### ISSUE TITLE
Rickon is able to cancel Kotl version Euron's Intimidate

### ISSUE THREAD

**Issue by Adolomin** [throneteki/throneteki#2437]
Rickon's ability is able to trigger during opponents use of Euron's intimidation. I've been able to duplicate it every time so far in matches and it can be avoided by just skipping the action, but just letting you guys know its there.

**Comment by ystros** [comment]
Thanks for the report! This bug is because Rickon is looking at the full card text instead of just the text for ability being initiated. Doing a proper fix for this might be difficult (since there's no good way for us to segment the text per ability) but there may be quick hacky ways of fixing it.

**Comment by Martozar** [comment]
@ystros the same applies for Aegon. Rickon can cancel his shadow which is confusing sometimes
