### ISSUE TITLE
Rickon able to cancel abilities from characters with the text "search"

### ISSUE THREAD

**Issue by SteliosCh21** [throneteki/throneteki#2464]
![rickon glitch](https://user-images.githubusercontent.com/46503013/55895185-4d4b2a00-5bc4-11e9-83b2-4848e4943c8a.png)
![bug](https://user-images.githubusercontent.com/46503013/55895241-6f44ac80-5bc4-11e9-90d5-eff7d4c8102b.png)

**Comment by cryogen** [comment]
Not sure what this issue is about, but this is Rickon's card text:

**Interrupt:** When the effects of a triggered ability with the word "search" in it would initiate, sacrifice Rickon Stark to cancel those effects.

In your screenshot this seems to be working as intended

**Comment by SteliosCh21** [comment]
With Margaery yes, with Euron's intimidate he shouldn't. I'm sure I've seen him in other instances also, I'll make sure to PrtScn it next time.

**Comment by cryogen** [comment]
Got you now, thanks! Figured I was missing something

**Comment by ystros** [comment]
Thanks! As mentioned, Rickon should be able to cancel Marg's ability, but not her renown, and similarly not Euron's intimidate. Fix on the way.
