### ISSUE TITLE
King's Gate and Core Euron Crow's Eye

### ISSUE THREAD

**Issue by Adolomin** [throneteki/throneteki#2468]
Core Euron Crow's Eye's ability to grab King's Gate. The ability to sacrifice the King's Gate by the opponent for card draw currently allows me (instead of the opponent) to have said card draw. Sorry if worded weirdly.

**Comment by ystros** [comment]
Thanks for the report! This looks like a problem with all the Gate cards - they're improperly looking at the controller after the sacrifice happens (once it's in the original owner's discard pile) rather than the player that triggered it.
