### ISSUE TITLE
theironthrone.net not sending verify email

### ISSUE THREAD

**Issue by AresGodlike** [throneteki/throneteki#2469]
Hey,

trying to create an account to https://theironthrone.net/. 

All goes well until i should verify my account via email verification as i dont get any verification email. 

I tried registering with two different emails and both had the same problem, no verification emails.

Hope we can solve this problem somehow and I'd be able to start learn the game of thrones card game =)

**Comment by cryogen** [comment]
Please can you confirm your account name?

**Comment by cryogen** [comment]
Thanks.  Just checked the email logs.  Hotmail rejected the message due to the mail server being blacklisted.  I've manually verified you.

**Comment by AresGodlike** [comment]
ok ok thank you. i'll go check out if can log in now
