### ISSUE TITLE
Ghost of High Heart have no effect

### ISSUE THREAD

**Issue by Toomagic** [throneteki/throneteki#2491]
Hello, I tried to play a game with the card "Ghost of High Heart" and it had no effect : no boost from +1 since I had no loyal character and no possibility to do his action. I hope you can resolve this one soon !

Thanks again for all the great work you do freely for this community !
You're the best team !
Xoxo

**Comment by cryogen** [comment]
Thanks for your report. As you can see from this list https://github.com/throneteki/throneteki/issues/2377 that card has not been implemented yet. Hopefully it will happen soon, or if you’re able feel free to claim it and give it a go!
