### ISSUE TITLE
User name colors in chat are white for system messages like concede/leave/disconnect

### ISSUE THREAD

**Issue by Saviouress** [throneteki/throneteki#2492]
Since the latest update the chat messages for leaving a game appear with a white username (just like regular messages), but on the usual light blue or light green background, this is unreadable.
![users](https://user-images.githubusercontent.com/25232040/56812508-516d7d80-683b-11e9-868d-aadcf0f98d83.jpg)

**Comment by cryogen** [comment]
Fixed by throneteki/throneteki-client#59

Fix should be live now
