### ISSUE TITLE
Gates of the moon doesn't give +1 gold to opponent...

### ISSUE THREAD

**Issue by Saviouress** [throneteki/throneteki#2503]
... when fetched via Varys's Riddle during Plot Phase.

**How to reproduce:**
1. Plot oppenings: Varys's Riddle vs At the Gates.  
2. Fetch Gates of the Moon.  
3. Opponent won't get the +1 gold modifier from Gates of the Moon.  

This might be a b**** to fix, because it involves Riddle.

Relevant links:
[Gates of the Moon](
https://github.com/throneteki/throneteki/blob/master/server/game/cards/08.2-JtO/GatesOfTheMoon.js)  
[At the Gates](https://github.com/throneteki/throneteki/blob/master/server/game/cards/13.1-AtG/AtTheGates.js)  
[Varys's Riddle](https://github.com/throneteki/throneteki/blob/master/server/game/cards/04.1-AtSK/VaryssRiddle.js)

**Comment by ystros** [comment]
Thanks for the report! Despite being a complex interaction, it was easy to reliably reproduce. Fix on the way.

**Comment by Saviouress** [comment]
Thanks I'm looking forward to find out what the problem was.  
I tried digging through the card code, but couldn't quite figure it out.
