### ISSUE TITLE
Registration

### ISSUE THREAD

**Issue by Fredmcragae** [throneteki/throneteki#2510]
Hi there,

I would like to registrate at "theironthrone.net", which i did.
Only problem is that i don't get the verification e-mail.

My e-mail is marc.de.graef@hotmail.com
username : Fredmcragae

I hope you can help me experience this game.
Many thanks in advance 
Sincerely Marc.

**Comment by cryogen** [comment]
We seem to be having issues with getting emails to delivered to hotmail at the moment.

I've manually verified you and will close this issue and remove your email address from it so you don't get spammed.

Thanks
