### ISSUE TITLE
Ghost of High Heart and cancels

### ISSUE THREAD

**Issue by Odrl7** [throneteki/throneteki#2514]
There was a slight problem when I tried to use Ghost of High Heart against Greyjoy and my opponent had Drowned God Fanatic in hand. I was able to look at his hand and select a card I wanted to discard, and only then did my opponent get the opportunity to use the Fanatic and cancel Ghost's ability. The interrupt window should open before the hand is revealed.

I assume Begging Brother or Treachery would have the same problem when interacting with GoHH, but I haven't tested it.

**Comment by ystros** [comment]
Thanks for the report! Yes, the target choosing is currently happening prior to resolution of the effect, instead of as part of the effect, so the "look at hand" portion happens too early. The wording of this card was especially annoying.
