### ISSUE TITLE
Vanquish the Unbelievers Freezing Game

### ISSUE THREAD

**Issue by jdvmartell** [throneteki/throneteki#2522]
After flipping the plot "Vanquish the Unbelievers" the game prompts you to type in a trait, then you click "Done" and the game usually progresses.  Today at around 1:00PM EST (USA) on both Chrome and Firefox the "Done" button clicked, but did nothing, thus freezing the game.  No further prompts or action could be taken besides closing the browser.

Hope this gets fixed as this plot is very popular!

Thanks

**Comment by jdvmartell** [comment]
![Screen Shot 2019-05-14 at 12 54 41 PM](https://user-images.githubusercontent.com/50633952/57717516-7179ab00-7649-11e9-83f2-372ef575cee2.png)

**Comment by cryogen** [comment]
This is fixed in https://github.com/throneteki/throneteki/pull/2521 but not yet deployed
