### ISSUE TITLE
Throneteki doesn't work on my computer

### ISSUE THREAD

**Issue by Neoptolemos** [throneteki/throneteki#2532]
Hey, I have strange problem with throneteki on my computer - since wednesday the site doesn't work for me, there is only black screen - while it worked perfectly earlier. What is more, on other computers everything is fine. Is it some problem with my IP address, internet connection or something else?

**Comment by jbrz** [comment]
Throneteki is run in browser, so it's highly unlikely 'your computer' is the issue.

If you don't provide technical details (OS, browser, browser version, etc.) it's quite impossible to provide you with any support.  Best I can say is to try and update your browser.

**Comment by Neoptolemos** [comment]
Thanks, I already cleared my cache and it works now. I don't know what was the issue (I use Chrome), but apparently it is working now. Strange though.
