### ISSUE TITLE
Warhammer + Azor Ahai Reborn

### ISSUE THREAD

**Issue by peejieweejie** [throneteki/throneteki#2594]
I may have a rules misunderstanding with the intimidate, but here goes. I have FOTS Stannis with Azor Ahai Reborn and a Warhammer. His str is not added to attacking rhllor characters, and neither is the intimidate.

**Comment by peejieweejie** [comment]
It works now, but if the Rhllor character is killed mid challenge, the person with the attachment is still in the challenge, which I think is wrong. For instance, killed with catapult or Robert strong.

**Comment by ystros** [comment]
Thanks! I haven't had time to confirm your second report, but if that's bugged them it's probably bugged for similar cards (Core Jon Snow, Walder Frey, etc)
