### ISSUE TITLE
Every Captain Is A King effect lasts for only one Power challenge

### ISSUE THREAD

**Issue by HumbleBob** [throneteki/throneteki#2595]
After playing Every Captain Is A King, Captains will be knelt when declared as attackers in Power challenges after the first.  Can't confirm if King trait is still applied or not.

**Comment by ystros** [comment]
Thanks for the report! I confirmed the second attacking power challenge kneeled the Captain, but the card is definitely programmed to be "until end of phase". Very curious, will have to dig in more.

**Comment by HumbleBob** [comment]
I had what might have been a similar issue in another game: the non-kneeling effect of "There Are No Men Like Me" did not register the second time I tried to use the same character in a military challenge.  It might be worth noting that this time, I played my event, my opponent then played "No Surprises," and then the effect didn't register for the second military challenge.  The "No Suprises" might have been unrelated, of course, but it did strike me that it may have had something to do with it.
