### ISSUE TITLE
Political Disaster, locked dead pile and Pyramancer's Cache

### ISSUE THREAD

**Issue by Neoptolemos** [throneteki/throneteki#2600]
Hey, there are 3 issues to solve - 2 of them didn't exist previously.
1. It is impossible to drag a character from dead pile to discard in case of mistake
2. Political Disaster discards even duped locations
3. Pyramancer's Cache still doesn't work

First two problems are new, because they weren't a problem several weeks ago. Cache wasn't still implemented, I think.

**Comment by ystros** [comment]
Thanks for the report!

1. Confirmed you can no longer drag from dead to discard, definitely a new bug.
2. I couldn't reproduce a problem with Political Disaster. The duped location I didn't select was properly saved by the duplicate.
3. The "gain text" portion of Pyromancer's Cache is much trickier than it might sound. I'm not going to implement it as part of this issue, but it should get implemented eventually. It automates the harder part for you (blanking the location), you should be able to do manual things to simulate the missing kneel-to-draw behavior.

**Comment by ystros** [comment]
As an update, I've been able to reproduce the Political Disaster bug, but not in a consistent way. It's fairly strange.
