### ISSUE TITLE
Outlook registration

### ISSUE THREAD

**Issue by Kradirhamik** [throneteki/throneteki#2610]
Hi,

Just registered with my Outlook email (the only one I got!), however I received no confirmation email. Can you help please?

**Comment by cryogen** [comment]
Is this the same username that you’ve registered to the site with?

**Comment by Kradirhamik** [comment]
Yes, same username as here in Github

**Comment by cryogen** [comment]
Thanks, I’ve manually verified it for you.  Our emails are being blocked by Microsoft unfortunately

**Comment by Kradirhamik** [comment]
I can't seem to spectate a game. Is there a bug regarding this?
