### ISSUE TITLE
Dothraki Steed

### ISSUE THREAD

**Issue by Toomagic** [throneteki/throneteki#2654]
Now that you fixed the bug where Dothraki Steed applied the buff permanently, it does not apply the buff at all, even during challenges.

Sorry for the bad news, as usual kuddos for all the great job you're doing for us !!!
Love ya guys !

**Comment by ystros** [comment]
Thanks for the report! I'm pretty sure this is already fixed by #2645, but it may not be on the site yet.

**Comment by ystros** [comment]
The fix should be on the site now.
