### ISSUE TITLE
Forced March initiates even if the effect will not change the game state

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2663]
As per ruling
http://www.cardgamedb.com/forums/index.php?/topic/39867-ruling-forced-march-ygritte-ser-barristan-selmy/ 

one can't just kneel own characters if opponent has no more characters with military icons to kneel. However the resolution of the plot on TiT allows that as seen here
![unknown](https://user-images.githubusercontent.com/39171688/60923066-caab3700-a2a6-11e9-9763-25666274b20b.png)

**Comment by ystros** [comment]
Thanks! I'll have to look at this more closely, as it looks like we do have a check in place for this, but it may not be working properly.

While looking at this card, we should also attempt to make the "initiate again" portion cancellable by Outwit / Someone Always Tells per this ruling: http://www.cardgamedb.com/forums/index.php?/topic/40071-ruling-forced-march/
