### ISSUE TITLE
Azor Ahai Reborn problem

### ISSUE THREAD

**Issue by Metch85** [throneteki/throneteki#2685]
I just played with a player who attached Azor Ahai Reborn to Robert Baratheon.
He declared a challenge with one R'hllor character. So Robert is considered attacking too.
I used my Highgarden to remove the attacking R'hllor character.
FAQ said Robert shouldn't be considered attacking anymore, 
but the game considered Robert still attacking.

Please let me know if i misunderstood!

**Comment by ystros** [comment]
Thanks for the report! You're correct on the ruling. 

We added a test in #2647 to check that this was working and it seemed to be. Unsure if we did something else that fixed it. If you encounter this again, please re-open the issue!
