### ISSUE TITLE
Registering problem

### ISSUE THREAD

**Issue by Daamant** [throneteki/throneteki#2729]
Hi, I have some problems with the registering. I have registered 3 times, with 3 differents e-mail adress since it was said that hotmail adresses have some problems, but I never received any confirmation/activation mail with any "account" yet.
Tried to contact the owner via twitter or patreon but don't know if he saw this.

My account username is "Damant" using an hotmail.com email.

If someone can help ^^

Thanks!

**Comment by Daamant** [comment]
my other attempted account are made using aol.com  email (username Daamant) and outlook.fr email (username Desmon).
But if we can use the first one, since it(s the same username I used on thronesdb.

**Comment by MojoSoDopeZH** [comment]
Hi
I have exactly the same problem. Would be great if someone could help.
Thanks

**Comment by cryogen** [comment]
Both of the above accounts have been verified. Sorry for the delay.

**Comment by MojoSoDopeZH** [comment]
Thank you cryogen. Apparently my account MojoSoDopeZH is still not working. It says the verification is still neeeded. Could you please check and advise. Thank you.
