### ISSUE TITLE
Azor Ahai Reborn participation

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2731]
Hello,

Stannis has Azor Ahai Reborn, Acolyte is initiating a challenge which makes him paticipate, then the acolyte is killed by Robert Strong and Stannis should not participate any more, though he does. Seems like a bug. See screenshot.

Sergey
![Bug](https://user-images.githubusercontent.com/39171688/64487819-fe272500-d247-11e9-9623-c64acc776d2d.PNG)

**Comment by ystros** [comment]
Thanks for the report and the screenshot! We have tests that say this should work, but they use explicit challenge removal (e.g. Highgarden). This is likely a bug with removal from the card leaving play (in this case, being killed) instead. Will need to look closer.
