### ISSUE TITLE
Forest Patrol bug

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2732]
Forest Patrol has "No attachments except weapon", however Crown of Gold was attached to it on throneteki.
![Bug2](https://user-images.githubusercontent.com/39171688/64487834-37f82b80-d248-11e9-9b33-cdf875b8069b.png)

**Comment by ystros** [comment]
Thanks for the report! The problem seems to be that the Shadow and No attachment keywords are on different lines and we're not handling it properly. Up until now, all keywords always appeared on the same line.  Fix is on the way.
