### ISSUE TITLE
Bloody Cup cannot be saved from

### ISSUE THREAD

**Issue by imrahil327** [throneteki/throneteki#2757]
The Greyjoy event "The Bloody Cup" currently does not allow characters targeted by it to be saved by duplicates.  It is correct that Bodyguard, Risen from the Sea, etc, cannot save, but duplicates should be able to prevent the character from being returned to the top of the deck.

**Comment by ystros** [comment]
Thanks for the report! Definitely a bug in how we handle "put on top of deck" vs duplicates.
