### ISSUE TITLE
Karhold didn't work

### ISSUE THREAD

**Issue by Tytos-Lannister** [throneteki/throneteki#2783]
I was playing a game with Karhold on the board on my side, I had A time for wolves and the opponent was playing Greyjoy and had revealed You win or You die.

Despite nor having a winter plot he still was able to claim power with Euron and Corpse Lake (no nightmares, seized or other negative attachments were in play).

**Comment by stephenomaze** [comment]
Can confirm that Corpse Lake still gains power without winter plots while Karhold is out.  I haven't seen characters contineu to gain power.
