### ISSUE TITLE
Blood Magic Ritual does not blank opponent's characters

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2838]
An opponent played Blood Magic Ritual on my Bob (saved him from kill), however the game still presented to me the options to trigger Robert's ability or gain renown, hence BMR did not properly blank it.
![BMR bug](https://user-images.githubusercontent.com/39171688/68506643-18e33d80-027b-11ea-9345-7aeab7ae65ac.png)

**Comment by ystros** [comment]
Very good catch! Fix is on the way.
