### ISSUE TITLE
Tormund Giantsbane Effect Duration

### ISSUE THREAD

**Issue by teamjimby** [throneteki/throneteki#2869]
I played a game with Tormund Giantsbane and noticed a bug with his +2 STR and renown action.  In my game it applied renown only to the **first challenge** that he (and another Wildling) won, when it is supposed to be until **end of phase**.  Renown was not applied to additional challenges, although the +2 STR remained.  See below.

![image](https://user-images.githubusercontent.com/41034707/70158164-6a18fe00-167c-11ea-8abb-05f4900bde27.png)

**Comment by teamjimby** [comment]
In subsequent games the STR buff also did not last until end of phase.  I'm not sure why it worked the one time but not the other.

**Comment by teamjimby** [comment]
I tried today and the effect is still expiring after the first challenge.

**Comment by ystros** [comment]
The change likely isn't on the site yet. Probably will go out around the time Thing We Do For Love Pack does in January (or earlier if more changes are made).

**Comment by teamjimby** [comment]
This bug is still happening even after the Things We Do For Love Pack got implemented.
