### ISSUE TITLE
Gathering Storm does notr return plot to plot deck

### ISSUE THREAD

**Issue by sergselin** [throneteki/throneteki#2925]
When my opponent decides to trigger the ability on my Gathering Storm, his previous plot stays in the used plots pile and not returns to the plot deck. Had to do it manually.
![Снимок2](https://user-images.githubusercontent.com/39171688/73609010-8254bd00-45da-11ea-9d78-ce4a8a1b8ad4.PNG)

**Comment by ystros** [comment]
Thanks! Fix on the way
