### ISSUE TITLE
Delena Florent stopping Ser Imry Florent from triggering

### ISSUE THREAD

**Issue by Odrl7** [throneteki/throneteki#2937]
I just had a game where Ser Imry Florent was mysteriously prevented from triggering in the challenges phase (the "force kneel" was greyed out), and there was nothing blanking him or preventing me from triggering abilities at the time.

Delena Florent was the only card in play that interacted with standing or kneeling in any way, so I suspect she must be the cause. Is there some sort of conflict that stops Imry from triggering if Delena Florent is in play?

**Comment by ystros** [comment]
Thanks for the report! Ser Imry's implementation was checking that cards were allowed to be stood instead of knelt, hence the bad interaction. Fix is on the way!
