### ISSUE TITLE
Archmaester Marwyn’s placed cards are lost

### ISSUE THREAD

**Issue by PeteCrighton** [throneteki/throneteki#2942]
It may just be because of my inability to spot the correct place, but I am of the opinion that the cards placed by [Archmaester Marwyn](https://thronesdb.com/card/15041)’s reaction are shown nowhere. I would expect to be able to click on my agenda (which is not [The Conclave](https://thronesdb.com/card/09045)) and see the two cards, but nothing happens. The log correctly shows two cards being placed, I just can’t see or interact with them anywhere.

**Comment by ystros** [comment]
Thanks! I had forgotten about this issue. When we originally implemented it we only put them under Conclave (since that's the biggest use case), so if you're not using Conclave you can't see them currently.

**Comment by Patane97** [comment]
Added/Resolved in #3502
