### ISSUE TITLE
Sansa Stark [Core] is knelt in setup

### ISSUE THREAD

**Issue by PeteCrighton** [throneteki/throneteki#2944]
When you place [Sansa Stark](https://thronesdb.com/card/01147) during setup, she is knelt and remains knelt when revealed, but she should be placed and revealed standing instead, as [cards are not considered to have been marshaled, played, put into play, or to have entered play when they are revealed or announced in setup, and card abilities that reference those terms are ignored during this step](https://thronesdb.com/rulesreference#Setup).

**Comment by ystros** [comment]
I can only reproduce this if you manually drag Sansa Core into the play area during setup. If you click her in hand (as you would normally do to set up cards), she is setup standing as expected.

**Comment by PeteCrighton** [comment]
Right on, that must have been what happened.
