### ISSUE TITLE
The wars to come bug

### ISSUE THREAD

**Issue by Djole9801** [throneteki/throneteki#2947]
Hey all, 
I was trying to make a deck and imported The wars to come as agenda and an error came up saying "Too few plot cards. More than 2 plot cards in rookey.". 
If this could be fixed it would be awesome!

**Comment by Djole9801** [comment]
Sorry guys, my bad.

**Comment by ystros** [comment]
Ha, no worries. Sounds like you pasted your deck list into the "Rookery" section instead of the "Cards" section?

**Comment by Djole9801** [comment]
> Ha, no worries. Sounds like you pasted your deck list into the "Rookery" section instead of the "Cards" section?

Yeah, kinda stressed out a bid and just tried it and it dawned on me. Sorry for the trouble!
