### ISSUE TITLE
Feature Request for the upcoming World Cup

### ISSUE THREAD

**Issue by MindsDesire** [throneteki/throneteki#2952]
I was wondering if it's possible to get a chess clock option for the timer so that games can be self policed when it comes to slow play etc. Chess clocks count down when it's your priority (action window) and you lose if your clock hits 0. This eliminates any enmity towards players for playing certain strategies and eliminates any chance of slow playing. There's a functional version that works for L5R and we use it for that World Cup.

**Comment by ystros** [comment]
I don't have any objections to this, other than it could be confusing to have both types of timers (overall time limit, and chess timer) available on the site.

Unfortunately, I don't have time to help with any implementation of this. Would be happy to review if someone else wants to attempt it.
