### ISSUE TITLE
Azor ahai + breaker of chains

### ISSUE THREAD

**Issue by davidalfalfa** [throneteki/throneteki#2954]
If you have both attachments attached to a character it allows you to trigger breaker of chains when you are not declaring as an attacker the attached character.

**Comment by Odrl7** [comment]
The same bug also happens if Motley is attached to the Azor Ahai character. It will allow you to trigger Motley any time a R'hllor character is declared as an attacker.

**Comment by ystros** [comment]
Thanks! Both Motley and Breaker of Chains were using an event that sent all attackers / defenders at the start of a challenge, not just declared ones. Fix on the way!
