### ISSUE TITLE
The Lannister "Gold Mine" draws the same card always

### ISSUE THREAD

**Issue by christorruella** [throneteki/throneteki#2962]
It happened to me twice already that every card I discard with Gold Mine is the next I get, like a loop.
I thought was just bad or good luck. And then this happened:
<img width="264" alt="Screenshot 2020-04-19 at 21 27 21" src="https://user-images.githubusercontent.com/21307486/79697817-3504f500-8285-11ea-946d-6db2b8610150.png">

A gold mine that got me a gold mine which at the same time got me the third gold mine in a row

**Comment by ystros** [comment]
As unlikely as this seems, this likely comes down to luck. There's nothing specific to Gold Mine nor the draw card mechanism in general that would do this.
