### ISSUE TITLE
Water Dancers Sword on Ser Lancel Lannister

### ISSUE THREAD

**Issue by dokempf** [throneteki/throneteki#2964]
Lancel (printed STR of 0) should be able to take Water Dancers Sword, but currently can't. I am fairly sure that @EvadLhorg 's fix in #2857 and specifically line https://github.com/throneteki/throneteki/blob/master/server/game/drawcard.js#L218 is the culprit. Btw, I checked Beric Dondarrion and Dacey Mormont and they work correctly.

**Comment by ystros** [comment]
Thanks, and nicely spotted!
