### ISSUE TITLE
Karhold + Corpse lake

### ISSUE THREAD

**Issue by davidalfalfa** [throneteki/throneteki#2968]
If you dont have a Winter plot card revealed still the option to gain power for corpse lake appears when a character is discarded from an opponent deck.

**Comment by EvadLhorg** [comment]
Hi!
Thanks for you report. Unfortunately, i am unable to reproduce the issue you describe. In my test game, the corpse lake player wasn´t able to trigger it when he had Time Of Plenty revealed while karhold was in play. Do you remember if there were any other circumstances in the particular game where you encountered the issue, for example was karhold blanked via nightmares?

**Comment by davidalfalfa** [comment]
Hi there! right now I think is like Gorold with Delena Florent, you can see the light and you can click on the corpse lake or on Gorold but nothing happen. I didn't click on corpse lake because I knew it wasn't legal but I've tried Gorold to test and he can't stand when the lady florent is on the board so probably this two examples are the same and both are well implemented. Thanks for checking :)

Obtener Outlook para Android<https://aka.ms/ghei36>
________________________________

**Comment by EvadLhorg** [comment]
Thank you for your response, i will let this issue be closed then :)
