### ISSUE TITLE
City of Secrets

### ISSUE THREAD

**Issue by chumbert1834** [throneteki/throneteki#2971]
City of Secrets does not make the player without a kingdom plot discard 2 cards

**Comment by ystros** [comment]
Seems to work for me. 
<img width="1789" alt="Screen Shot 2020-05-01 at 10 22 02 PM" src="https://user-images.githubusercontent.com/145077/80855950-74730000-8bfa-11ea-849d-d56b29251159.png">

To be clear, the condition for City of Secrets is whether they have a City plot in their used pile: https://thronesdb.com/card/13019

Could you provide exact reproduction steps?

**Comment by Odrl7** [comment]
I had this issue a while back and couldn't figure out what was causing it. If it's any help:

![CityofSecrets](https://user-images.githubusercontent.com/43860949/82727316-02b63f80-9cea-11ea-8825-04b0d2b1ce54.png)

Unfortunately I didn't take a screenshot of the board state at the time, but I definitely didn't have any City plots in my used pile. Opponent was playing Rains of Castamere and had one plot removed from the game (but it wasn't City of Spiders) if that's in any way related, although I can't see how it could be.

**Comment by ystros** [comment]
@Odrl7 Thanks. I think I see the bug (and other unrelated bugs). Do you happen to remember if you or your opponent had less than 2 cards in hand before the 2 card draw happened?

**Comment by Odrl7** [comment]
I can't say for sure, but I think it's very likely that I had 0 cards in hand before the draw, or 1 at most.
