### ISSUE TITLE
Outwit vs Valar Dohaeris

### ISSUE THREAD

**Issue by dokempf** [throneteki/throneteki#2996]
When these two plots are resolved, the chosing of targets for VD happens before the cancel interrupt of Outwit, which I believe is correct. However, the prompt for cancel does not appear when I do not chose a unique maester character as the target of VD. This is wrong of course as all characters are still on board when the interrupt triggers.

**Comment by ystros** [comment]
I wasn't able to reproduce this.

* Each player set up a bunch of cards, including Grand Maester Pycelle for Player 1
* Player 1 revealed Outwit, Player 2 revealed Valar Dohaeris
* VD selections happen as expected. Player 1 purposefully does not select Pycelle.
* After VD selections, Player 1 is prompted to initiate Outwit as expected.
<img width="1789" alt="Screen Shot 2020-06-02 at 7 53 11 PM" src="https://user-images.githubusercontent.com/145077/83590497-bdc0b300-a50a-11ea-8a68-70d380632c23.png">


```
test1 has selected a plot
test2 has selected a plot
test1 reveals Outwit
test2 reveals Valar Dohaeris
test2 won initiative
test2 has selected test1 to be the first player
test1 chooses Tommen Baratheon, Lannisport Merchant, and Joffrey Baratheon for Valar Dohaeris
test2 chooses Arianne Martell, and Dornish Spy for Valar Dohaeris
test1 uses Outwit, kneels their faction card, and kneels Grand Maester Pycelle to cancel Valar Dohaeris
```

**Comment by dokempf** [comment]
Oh, that is weird, especially as your setup matches mine. I will check again and reopen if the problem persists.
