### ISSUE TITLE
issues with actions in dominance phase

### ISSUE THREAD

**Issue by scottludwig** [throneteki/throneteki#3001]
hello,

I have had multiple issues with the game passing over/not allowing actions to be triggered in dominance phase. This includes "dominance actions" and regular "actions".

**Comment by ystros** [comment]
Hi @scottludwig! By default, the site does not enable the action windows for phases like dominance that don't have a lot of abilities associated with them. You should enable the action windows you want on your Profile page (click Dominance phase, then the Save button at the bottom of the page), or you can enable it by clicking Game Settings during individual games.
