### ISSUE TITLE
Marshalling into Shadows Issue

### ISSUE THREAD

**Issue by PGedi** [throneteki/throneteki#3003]
For some reason there appears to a problem with putting a card into shadows. I saw this on a game earlier, and had my opponent have the problem earlier. In my game, I had revealed Barring the gates and my opponent the first snow of winter, I’m not sure if that helps, but thought I would mention.

Thanks 
Paul

**Comment by EvadLhorg** [comment]
Thanks for the report and the detailed description, fix is already on its way!

**Comment by ystros** [comment]
I think the fix for this is now deployed (or if not, probably will be within a week)
