### ISSUE TITLE
Cersei + Missandei = Server Error

### ISSUE THREAD

**Issue by jimorie** [throneteki/throneteki#3005]
There seems to be some issue with Cersei Lannister when interacting with cards that interrupt their own discard effect. Saw instances of it with both Missandei and Ser Jorah Mormont. See attached screenshots:

<img width="1436" alt="Screen Shot 2020-06-24 at 10 14 06" src="https://user-images.githubusercontent.com/2361594/85521038-f92f3880-b603-11ea-8552-cbe01ce12db2.png">
<img width="1432" alt="Screen Shot 2020-06-24 at 10 09 27" src="https://user-images.githubusercontent.com/2361594/85521052-ffbdb000-b603-11ea-84fd-f7d49a7b8f14.png">

**Comment by ystros** [comment]
Just want to say thank you thank you thank you @jimorie for the report + screenshots. We've been seeing this error pop up on the backend for months but had no information about the interaction causing it. It may still be tricky to fix, but at least we know exactly what **needs** to be fixed.

**Comment by jimorie** [comment]
Happy to help you and the team in your glorious work, @ystros! :)
