### ISSUE TITLE
Ser Imry Florent used when controlled by opponent

### ISSUE THREAD

**Issue by DeividDAVE** [throneteki/throneteki#3012]
Ser Imry Florent: https://es.thronesdb.com/card/14011

When Ser Imry is being controlled by your opponent due any reason, like Ward, it creates an ill situation.

If the opponent kills him to destroy locations and kneel opponent characters, the game gives him the option to destroy his opponent locationss (instead of his own ones), which should not go this way.

I think because he is first killed, and then goes straight to owners dead pile, and at that very moment is again controlled by the owner, so at the moment to sacrifice locations, it markes the owner (and again controller) locations.

**Comment by ystros** [comment]
Thanks for the report! However, I cannot reproduce this. I took the following steps:

1. Set up each player with locations.
2. Set up Imry Florent with the Baratheon player.
3. Took control of Imry using Ward with the Stark player.
4. Activated Imry's ability.
5. I was prompted to sacrifice locations for the Stark player as expected.

<img width="1786" alt="Screen Shot 2020-06-30 at 9 29 32 PM" src="https://user-images.githubusercontent.com/145077/86203247-687fbd80-bb19-11ea-9bca-745d2f2571a4.png">

I'm fairly confident this is related to a fix made in late March. #2928 Were you playing on `theironthrone.net` or some other server?

**Comment by DeividDAVE** [comment]
Dear ystros, thanks for answering.

Yeah, I think our problem came because we were playing on an instance which probably had a previous patch version.

Thanks for your time, the ticket can be closed.
