### ISSUE TITLE
Winterfell Crypt doesn't allow saves

### ISSUE THREAD

**Issue by Element-25** [throneteki/throneteki#3016]
I had a situation where I had a Viserion with a duplicate that had been chosen for a Winterfell Crypt. At the end of the phase, I was not given the choice to save the Viserion which was just shuffled in my deck (the duplicate was discarded)

**Comment by EvadLhorg** [comment]
Hi! Sorry for the late reply. I have a follow-up question to your issue: Did you have "prompt before saving dupes" active in your user settings when you experienced the bug? Thanks!

**Comment by Element-25** [comment]
I did have it active
