### ISSUE TITLE
Taking the black cannot be initiated

### ISSUE THREAD

**Issue by Laconda** [throneteki/throneteki#3028]
Hi,

I have the problem that in the dominance phase there is no window to initiate "Taking the black". After challenge phase it skips directly to who wins dominance. No asking for actions.

Greetings, Laconda

**Comment by SotirisKantz** [comment]
Hi Laconda,
At the dominance phase, first it calculates-compares dominance and second there are the actions. Only at the action window you can play the "Taking the black". If there is no window, go to your profile and click on every one you want to appear. . 
![S00728-11091725](https://user-images.githubusercontent.com/24796302/88645704-b958e680-d0c4-11ea-8070-2c1a7a215c4b.jpg)

**Comment by Laconda** [comment]
Thank you very much, it helped! When I first read the "How to play..." I didnt recognize this.
