### ISSUE TITLE
Fight to the Last doesn't save from burn

### ISSUE THREAD

**Issue by ChannelDelibird** [throneteki/throneteki#3032]
Hey pals, thanks for all you do for this site!

Just had a game where I didn't get a prompt to use the Fight to the Last in my hand to save from a Drogon (IDP) trigger, which should work as the save sets STR to 1, preventing immediate death from terminal burn. A spectator said they'd found it wasn't implemented properly either. Seems to be fine for other methods of death.

**Comment by EvadLhorg** [comment]
Thanks for the report! Fix is on the way
