### ISSUE TITLE
Archmaester Marwyn doesn't work outside of Conclave

### ISSUE THREAD

**Issue by ChannelDelibird** [throneteki/throneteki#3039]
Look, I know. I _know_. But I did try it, and I'd like to try it again. Was using Banner of the Watch, should that matter, and when I triggered his reaction, the chat log told me it had done it, but there were no cards under my agenda.

**Comment by EvadLhorg** [comment]
Duplicate of #2942

**Comment by EvadLhorg** [comment]
Thanks for the report and bringing this up again!

**Comment by Patane97** [comment]
Added/resolved in #3502
