### ISSUE TITLE
trade routs showing as banned using 2.0 faq

### ISSUE THREAD

**Issue by scottludwig** [throneteki/throneteki#3061]
Hello,  I was under the impression that the conclave FAQ 2.0 was the one that used the new PODs system for restricted cards for joust.  Is that correct? If so iron thrones is listing trade routs as banned and not restricted.

Thank you,

**Comment by ystros** [comment]
Hi @scottludwig! Trade Routes wasn't one of the cards in a restricted pod in the Conclave 2.0 RL, simply restricted (so you couldn't use it with another restricted card). If it is showing up as "Banned" when validating against the Conclave 2.0 RL, you may have added the redesigned version of Trade Routes to your deck. All redesigned versions are banned in the Conclave 2.0 RL. It would show up as "Trade Routes (R)" in the deck builder if that's the case.
