### ISSUE TITLE
Arya core : unable to use face down card as a dupe to save against some plots

### ISSUE THREAD

**Issue by Trouveur** [throneteki/throneteki#3064]
It happened to me two times :

- first against the plot "First snow of winter", I have Arya with a facedown card as a dupe, but when challenge phase ended, she returned directly in my hand and the dupe was discarded, I didn't got a prompt to use the dupe to save her.

- second against the plot "Valar Morghulis", I have Arya with a facedown card as a dupe, but when the plot triggered, she was killed and the dupe discarded, without a prompt to save her. Weird thing too, I could see which card was facedown by hovering mouse cursor on it before the kill.

**Comment by EvadLhorg** [comment]
Hi and thanks for your report. Do you remember if there was any effect in play that prevents saving from being killed like Arya Stark (TFM) or the plot The Bloody Flux?
I just created a test game for myself and without any other effects in play i was able to use arya´s facedown dupe to save against valar m.
Any further info is appreciated!

**Comment by Trouveur** [comment]
Hello, no, to my knowledge there wasn't any effect preventing the save.

I will try to reproduce it with a friend and take some screenshots then.
