### ISSUE TITLE
Improvement: Adjust the UI for Banner Agendas under the Alliance agenda

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3072]
Banner Agendas which are clickable because they have Actions may be too "hidden away" when using the Alliance Agenda. Currently, you would have to click on the Alliance to open the Banner Agenda Card pile and then click on the Agenda with the action.
Feedback on how to improve this welcome

**Comment by Patane97** [comment]
Added feature in #3502 (shows alliance banners in lobby, and tucks additional agendas behind the primary on gameboard)
