### ISSUE TITLE
Unable to Reveal New Plots After Cycling

### ISSUE THREAD

**Issue by jpmckenna90** [throneteki/throneteki#3074]
Here's a fun bug. Tyrell White Book vs. Martell Wolf, original designs and RL. My opponent and I cycled plots, and when the 7th round was finishing, taxation seemed to end and then the plot phase didn't allow us to choose new plots, but instead "re-revealed" the ones that were revealed the prior round. See screenshots for board state and log:

![ss1](https://user-images.githubusercontent.com/27628608/100802174-0512f800-33f7-11eb-9a5d-b5815c4e6601.JPG)
![ss2](https://user-images.githubusercontent.com/27628608/100802179-080de880-33f7-11eb-93b5-a29b74cd337d.JPG)

**Comment by EvadLhorg** [comment]
Thanks for the report. Really weird...
Did you use Change of Plans or any other plot interacting card by any chance? Wasn´t able to reproduce this on the first or second try and i am looking for stuff that could lead to this weird behavior.

**Comment by jpmckenna90** [comment]
Nope, nothing that interacts with plots. We just revealed our round 7 plots, basically each passed the turn all the way through the round and then upon the end of the round, the reported behavior occurred.
