### ISSUE TITLE
Baelor Blacktyde and Annals of castle black interaction

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3100]
This was mentioned in one of the community discord servers:

"There is a slight problem with Baelor Blacktyde and Annals. He will stop you playing events from the discard pile even if you only have a single copy there, but ThronesDB says you should be able to play them."

**Comment by ystros** [comment]
A bit surprised at this ruling, since "cannot" generally outweighs any permission granted by other cards. But sure.

This probably will be difficult to fix.

**Comment by Odrl7** [comment]
In this instance we actually have an official ruling from Danny Schaefer:

"If there is a single copy of an event in your discard pile, you are able to play that event from your discard pile even if Baelor Blacktyde is in play (similar to the how it works when bringing a unique character out of your dead pile)."

I guess an event in your discard pile isn't considered to be a "copy" of itself, so it's not affected by Baelor unless you have more than one in the discard pile.
