### ISSUE TITLE
Bound for the Wall and Citadel Archivist

### ISSUE THREAD

**Issue by Odrl7** [throneteki/throneteki#3102]
There is a slight problem when Bound for the Wall (R) discards Citadel Archivist. You are prompted to trigger the Archivist before having to choose the character for Bound, so Bound just fizzles. What should happen is that Bound should resolve in full, and only then can the reaction of Citadel Archivist be triggered, if it's still in the discard pile. :)

**Comment by EvadLhorg** [comment]
Might be the same issue as this interaction https://github.com/throneteki/throneteki/issues/3085 ?

**Comment by Odrl7** [comment]
I'm not sure, but in terms of game mechanics this should be different, because it's nothing to do with an infinite loop. A better comparison would be Arianne/Ramsay. The game will return Arianne to hand before prompting you to choose a card for Ramsay, so that you can't choose her as the target.

Here Bound should prompt you whether you wish to do the "you may" part, and then it should prompt the opponent and let them choose the card they are giving you. Only after all of this is completed should the reaction window for a card being placed in the discard pile (the Archivist) open. In fact, I think Bound should even be placed in the discard pile before the Archivist triggers, so it should get shuffled along with everything else.
