### ISSUE TITLE
City of Wealth does not count the previous city plots

### ISSUE THREAD

**Issue by SotirisKantz** [throneteki/throneteki#3108]
Hi the City of Wealth does not count the gold, initiative and reserve from the previous plots or gulltown. It's stats are 2 2 1 2 no matter the number of city plots in the used pile. It was working fine before Jade Sea
![Screenshot from 2021-02-22 20-09-36](https://user-images.githubusercontent.com/24796302/108758351-496fe900-754b-11eb-98f7-8b472ab8355f.png)
.

**Comment by EvadLhorg** [comment]
Hi! Thanks for the report, this was already fixed a day ago with #3104 and the fix for it will be included in the next update

**Comment by SotirisKantz** [comment]
ok, great!
