### ISSUE TITLE
Lay Waste lets the player search even though the discarded card gets saved

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3112]
Title. According to thronesdb FAQ https://thronesdb.com/card/15044 the search should not happen when the card gets saved

**Comment by ystros** [comment]
Could not reproduce - played Lay Waste against a location with a dupe, dupe got discarded, no search was prompted.

<img width="1792" alt="Screen Shot 2021-03-15 at 9 42 30 PM" src="https://user-images.githubusercontent.com/145077/111257006-9178ad80-85d7-11eb-8552-9e894c76de66.png">
