### ISSUE TITLE
City of Wealth + Gulltown on Plot 9 doesn´t work

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3113]
Report from a community discord chat:
"there is some bug when you are at plot 9 and copying ability of City festival. It doesn't give the gold. (with Gulltown on table)"

**Comment by ystros** [comment]
Is this about City of Wealth (title) or City Festival (quote from discord)? Either way, there shouldn't be anything special about plot 9.

**Comment by EvadLhorg** [comment]
One more report from the community regarding this issue:
City of Spiders played as a 10th plot isn't working at all (8th plot was AtG)
