### ISSUE TITLE
Pycelle not allowed for agenda The Conclave?

### ISSUE THREAD

**Issue by Laconda** [throneteki/throneteki#3118]
Hi, 

though Grandmaester Pycelle is a Maester, he can not be integrated in a deck with "the Conclave" agenda when I play another faction. 

The agenda should allow Maesters of all factions. Is this a bug or am I missing something?

Greetings,
Laconda

**Comment by EvadLhorg** [comment]
Hello!

Pycelle is loyal and thus only usable in house lannister decks. Conclave only allows you too include non loyal maesters from any faction.

Best wishes!

**Comment by Laconda** [comment]
Oh, that I really missed. Thank you!
