### ISSUE TITLE
Loot pillage number selection

### ISSUE THREAD

**Issue by Aetherstorm** [throneteki/throneteki#3123]
When the X value on Loot goes above 15, I am unable to select a higher number due to the value options being fixed and not scrollable. I'm asking for a scroll or manual number select option to be added.

**Comment by EvadLhorg** [comment]
Hey mate, thanks for the report. This feature will be included in one of the next updates. See this issue https://github.com/throneteki/throneteki/issues/3082 and this pull request https://github.com/throneteki/throneteki/pull/3116

**Comment by ystros** [comment]
Update merged, closing this.
