### ISSUE TITLE
Reek is not coded as Unique

### ISSUE THREAD

**Issue by tfneptune** [throneteki/throneteki#3149]
Had a situation in the same game with Corn, Corn, Corn. I used Reek to gain an opponents character in the challenge phase. The next marshalling phase I tried to Ward him but it did not show up as an eligible target. I checked ThronesDB and there is no Unique symbol next to his name. That is the only thing I can conclude to why I could not Ward him.

**Comment by stopfstedt** [comment]
hot-fixed in TDB, see linked PR for fix in data repo.
