### ISSUE TITLE
BUG: kindly man does not remove betayal token off of jorah even though game log says so

### ISSUE THREAD

**Issue by stopfstedt** [throneteki/throneteki#3154]
_what's going on?_

kindly man does not remove betrayal token off of jorah, even though it get's logged in the in-game chat as such.
the token stays on jorah.

see screenshot for example:

![jorahkindlyman](https://user-images.githubusercontent.com/1410427/125726328-01cc415e-be3b-4192-a2d0-46ac92031e7b.png)

(never mind the  background, i'm running thronesdb proper with custom browser extension)

**Comment by stopfstedt** [comment]
adding on to this.

adding betrayal tokens to jorah using the kindly man seem to work, but now he stays on the board past his 3 token limit.

![image](https://user-images.githubusercontent.com/1410427/125727231-fa51adcf-1dbc-40be-aaaa-09d58df2f22d.png)

**Comment by stopfstedt** [comment]
adding on to this:

removing vengeance tokens via the kindly man off of the boneway doesn't work in the same way that it does't work with removing tokens off of jorah.

**Comment by ystros** [comment]
Thanks! Looks like removing tokens in general didn't work.
