### ISSUE TITLE
The Higher Mysteries and The Conclave

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3179]
Report by a community member:
When a challenge is won with a maester and I got the Higher Mysteries under the Agenda, then it forces me to activate first the Higher Mysteries under the Agenda and then the agenda. When the Mysteries are at hand, I have the option to use first the agenda and then the Higher Mysteries.

I think i found the issue with the client code in CardPile.jsx in the function onTopCardClick():
The code either activates the popup for the card pile (conclave pile) OR lets you click on the top card of the pile (conclave agenda). The isTopCardSelectable property is false (i think) in case you have a triggerable card in your conclave pile even though the conclave agenda card itself can be triggered.

**Comment by Patane97** [comment]
Resolved in #3502
