### ISSUE TITLE
Gifts for the Widow (R) bugged - stuck in cost prompt

### ISSUE THREAD

**Issue by stopfstedt** [throneteki/throneteki#3222]
I just ran into this issue twice - [Gifts to the Widow (R)](https://thronesdb.com/card/17135) prompts me to choose an attachment of cost X. I enter the gold amount but cannot submit the dialog.
In  both cases, there were targetable attachments in my deck and characters that can be targeted on the board. Had the right amount of gold too, faction card standing - all that stuff.

Example at hand:   
I play Targ/Stag. and have  2 gold remaining, My [Vanguard Lancer](https://thronesdb.com/card/01057) is on the board. I'm trying to fish out a [Warhammer](https://thronesdb.com/card/14022) and attach it to lancer. During the challenge phase, I play Gifts. I get prompted and enter "1"  and click the submit button. nothing happens, the prompt stays on the screen and the effect does not trigger. 

Not sure if the original version is bugged in a similar way, may be worth a look while at it.

Thanks!

**Comment by Zinthewin** [comment]
Workaround: only use the mouse/mouse pad to select the amount of cost (do not write it in with keyboard), and you should be fine :) Left click on text box and select the amount with another left click :)

**Comment by stopfstedt** [comment]
> Workaround: only use the mouse/mouse pad to select the amount of cost (do not write it in with keyboard), and you should be fine :) Left click on text box and select the amount with another left click :)

Just confirmed that this works. Thanks @Zinthewin !
