### ISSUE TITLE
Optional rule for Mulligans?

### ISSUE THREAD

**Issue by Laconda** [throneteki/throneteki#3226]
Hi,

this is just a proposition. I didn't know where to post. Maybe you can move the thread?

When we play, we allow more than 1 Mulligan. But for each one above you get 1 blood point on your faction card.
As long as you have those, you can not earn power.
Each time you would earn power, instead you can take away 1 of those blood markers.

So effectively, if you choose to take more than 1 Mulligan, you will start the match with a minus on power.

Maybe you could implement this as an option? What do you think?

**Comment by ystros** [comment]
It's an interesting idea. However, I don't think we'd be open to implementing custom home / kitchen table rules like this unless they were very widely adopted by the community, or officially endorsed by the Global Operating Team (e.g. as an optional rule or variant). 

You could likely do what you're describing manually using the existing interface, though somewhat painfully. E.g. drag your the cards in hand after your initial mulligan back to your deck, use chat commands to draw new cards, use the minus button for power to take away your first power after gaining it, etc.
