### ISSUE TITLE
Doran Martell (SoD) wrong reaction

### ISSUE THREAD

**Issue by Laconda** [throneteki/throneteki#3232]
After losing a challenge, instead of a choice for a character to lose a challenge icon, the game offers me to remove a character from the challenge.

**Comment by Laconda** [comment]
The option to do that Doran has during every challenge and it works fine.

Just the reaction on losing a challenge is the wrong one.

**Comment by Patane97** [comment]
Cannot seem to replicate this, Doran Martell (SoD) to be working absolutely fine by clicking on him, followed by "Select Card" once his reaction is open. You may be clicking the second option instead.

Closing this Issue, as it seems working.
