### ISSUE TITLE
Shuffle hand before discarding at random

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3258]
There have been multiple reports from the community that there is a perceived bias when discarding at random that the last/most right card in hand gets discarded. this gets noticed the most when effects like late summer feast (draw card to hand) or a pinch of powder (return card to hand) happen right before intrigue claim.
We might port over the discard at random effect from keyteki which shuffles the hand before discarding at random (https://github.com/keyteki/keyteki/blob/3eebdb1bf9c5ff932725bcfdea58ffa9b9b45d40/server/game/GameActions/RandomDiscardAction.js)

**Comment by cryogen** [comment]
Here's the results of a test of a million iterations. Looks pretty random to me

{
  '1': 166655,
  '2': 166754,
  '3': 167391,
  '4': 166898,
  '5': 165886,
  '6': 166416
}
