### ISSUE TITLE
Private Games are only private when you disable spectators

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3276]
Using the "Private (requires game link)" option for a game and combining it with the "Allow spectators" leads to the game being visible for everyone, which is probably not what is intended when hosting a private game

**Comment by cryogen** [comment]
Private means "noone can join without the link" not "this game is hidden". If it's hidden when spectators are disabled, then that's the real bug

**Comment by EvadLhorg** [comment]
Thanks for the explanation. The pending game is hidden in the game list. Once it is started, it shows up in the game list and spectators can join without the link. 
So i would say everything is working as intended and there is no "hidden game" feature
