### ISSUE TITLE
Shagwell and Patchface still give each other keywords from characters that are not in play anymore

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3299]
For example:
Shagwell, Patchface and Saltcliffe Sailor, all with 1 gold bestowed, are in play. They all have Stealth due to Saltcliffe sailor giving Stealth to bestowed characters. Now, Saltcliffe Sailor leaves play and Shagwell and Patchface should lose stealth.
At the moment, they still give each other stealth even though the source of stealth left play.

**Comment by Patane97** [comment]
Hmm, I definitely thought I fixed this with #3238. Can re-investigate when I get some time

**Comment by Patane97** [comment]
This seems to be a specific bug between Shagwell & Saltcliffe Sailor, and more specifically, that Shagwells `dynamicKeywords` ability is **reapplying** before Saltcliffe Sailor's passive `addKeyword` effect is **unapplying**. I believe to properly fix this one, there needs to be a _very deep_ investigation into the timing of dynamic effects.

`reapplyStateDependentEffects` is being applied...
https://github.com/throneteki/throneteki/blob/d3cd8bf1855400b08403cd64ad47b11d7a778611/server/game/effectengine.js#L61-L87

... before `onCardMoved` is being applied.
https://github.com/throneteki/throneteki/blob/d3cd8bf1855400b08403cd64ad47b11d7a778611/server/game/effectengine.js#L89-L94

@ystros @EvadLhorg Mind if I lend your thoughts on this scenario? I would have thought that we would always need to fully satisfy/trigger the `onCardMoved` event (which in turn should remove stealth from characters you control with gold) before recalculating the board state for effects (eg. Shagwell), but it doesn't seem to be the case here.

**Comment by Duckbringer** [comment]
I encountered similar issue, only this time it was 2 shaggwells and Horn of winter that was sacrificed
