### ISSUE TITLE
Losing my Discard and Dead pile window panes when playing on a smaller screen

### ISSUE THREAD

**Issue by 1jcarlyle** [throneteki/throneteki#3303]
Hey - my user ID is 1jcarlyle.  When I changed from playing on my monitors yesterday to my surface pro, I can no longer see the windows for discarded and dead piles - if I connect back to my monitors, I can see them but no matter where I move the window, it doesn't seem to put them in view anymore.  Help!

**Comment by cryogen** [comment]
Thanks for the report. The position of the window will have been saved. If you clear your browser local storage for the site, it will reset. If you don’t know to do this, here’s a guide for chrome: https://www.leadshook.com/help/how-to-clear-local-storage-in-google-chrome-browser/

failing that, clearing all site data will do the trick, but is a little more drastic.

**Comment by 1jcarlyle** [comment]
Ty!!!!
