### ISSUE TITLE
Heir to the iron throne revealing the whole deck

### ISSUE THREAD

**Issue by EvadLhorg** [throneteki/throneteki#3308]
Something seems up with the prompt for deck search.
![grafik](https://user-images.githubusercontent.com/6191998/193134586-cdfbdf23-fefd-49c3-9b23-27e084524997.png)

**Comment by ystros** [comment]
Which server was this on? Local main branch is fine:
<img width="1785" alt="Screen Shot 2022-09-29 at 9 18 40 PM" src="https://user-images.githubusercontent.com/145077/193189574-b36e3a47-0b72-4fbc-8837-8d1c05b8d79d.png">

**Comment by EvadLhorg** [comment]
Interesting, the screenshot was from the main server yesterday night. 
Just tested it again on the main server with a deck of my own:

![grafik](https://user-images.githubusercontent.com/6191998/193348953-58de793f-6235-4b2e-82e7-2210fc010c0e.png)

**Comment by EvadLhorg** [comment]
Even weirder: my local server on the current master commit is working for the reveal, but the sacrifice part is broken and showing all lords/ladies in all locations:

![grafik](https://user-images.githubusercontent.com/6191998/193349576-a6327e1b-5526-4b9f-a7f8-515f9a0e572c.png)

**Comment by ystros** [comment]
99% chance this is because the broken "Reveal" branch was deployed to the production site.
