### ISSUE TITLE
Last of the Giants not working

### ISSUE THREAD

**Issue by 1jcarlyle** [throneteki/throneteki#3317]
I was trying to use Last of the Giants today and nothing would happen when I clicked on it - tried it in both marshaling and challenge phases and yes, I did have the 2 gold to pay for it...  is the card not working right or am I missing something?

**Comment by Duckbringer** [comment]
I tested it now, and it seems to work. What I can think of is this:

- You did not have a neutral character in hand
- There was barring the gates revealed
- opponent had  baelor blacktyde 

If it happens again, please share a screenshot of the gamestate, preferably also with prior game state changes. Thank you

**Comment by 1jcarlyle** [comment]
Ty!!!!
