### ISSUE TITLE
Bug/Pulling the Strings-Exchange of information

### ISSUE THREAD

**Issue by Rorthgar** [throneteki/throneteki#3342]
![Screenshot_1](https://user-images.githubusercontent.com/124516922/216831047-c5bece26-5395-4b14-ab92-9adc9d3faa11.png)
I provide a screenshot of the game state at the of the bug 
Instead of revealing my deck it revealed the enemies deck and he could pick cards for himself

**Comment by Patane97** [comment]
Duplicate of #3336. Already fixed.
