### ISSUE TITLE
Storm's End and Lyn Corbray

### ISSUE THREAD

**Issue by Autoreply85** [throneteki/throneteki#3363]
I just had a game where my opponent had Lyn Corbray and Storm's End. I initiated a MIL challenge and he changed it to POW and stood Lyn Corbray, which caught me unexpected, because I was assuming that Storm's End does not change the type that is initiated, just how it is resolved. He was first player, if that matters.

Thronesdb also says that this should not be possible: https://thronesdb.com/card/22003

**Comment by ystros** [comment]
Will be fixed when #3364 is deployed.
