### ISSUE TITLE
Make viewing better on mobile

### ISSUE THREAD

**Issue by uBaHoB** [throneteki/throneteki#3424]
Will it be possible to just do the viewing on mobile better. Hide everything. No popups etc. Just the field and to be able to rotate and scale it a little.

**Comment by Patane97** [comment]
This is something which is a much larger piece of work than it may lead on to be, however it is currently being addressed in a separate project aimed to rework the entire website (being slowly worked on in our limited spare time).

Will close this issue, as this will eventually be resolved once that project is released. :)
