### ISSUE TITLE
The Fowler Twins effect apply during the actual challenge

### ISSUE THREAD

**Issue by LaranSoft** [throneteki/throneteki#3425]
If the action of The Fowler Twins is used mid challenge, before the defender declaration step, then the chosen character is forced to be declared as a defender in the current challenge.

**Comment by LaranSoft** [comment]
The implementation of two other cards with a similar effect: To The Spears and The Knight (MoM). Both of them are implemented in a different way from TFT, which actually ensures that the effect will be applied in the next challenge.

Maybe this could be solved by uniforming the implementation of TFT with the implementation of TTS / TK

**Comment by Patane97** [comment]
> The implementation of two other cards with a similar effect: To The Spears and The Knight (MoM). Both of them are implemented in a different way from TFT, which actually ensures that the effect will be applied in the next challenge.
> 
> Maybe this could be solved by uniforming the implementation of TFT with the implementation of TTS / TK

This unfortunately can't really work the same as TTS/TK, as this needs to be active *within* the 'onChallengeInitiated' event (to affect the declared attackers list), as well as during that challenge (to affect the declared defenders list). Unfortunately, `ChallengeTracker` only adds the challenge _after_ the 'onChallengeInitiated' event; this is why we see that TTS only checks that the number of initiated events are not greater than the number initiated when the event was played (as it should apply the next time you initiate attackers, meaning before that next challenge is added to the `ChallengeTracker` list.

We could potentially have either a global "challenge count" tracker which simply collates all players "challenge numbers" into a single value, as challenge number is specifically incremented _before_ initiation, as to work with things like LotR. Then Fowler Twins can simply save that number when triggered, and conditionally apply when that number is that saved number + 1. Technically a similar thing should be done for _any_ "next challenge" effects.
