### ISSUE TITLE
"A Cask of Ale" bug

### ISSUE THREAD

**Issue by sarabertoncelj** [throneteki/throneteki#3451]
There seems to be a bug with "A Cask of Ale" that lets you select opponents faction card and your own instead of two cards controlled by the same player. I added the screenshot, but there wasn't anything unusual going on that would prevent cards from gaining power. 

![image](https://github.com/throneteki/throneteki/assets/85683263/f0aca085-9cbd-4d33-b335-0067d586d33b)

**Comment by ystros** [comment]
Fixed by #3454
