### ISSUE TITLE
If Marwen is in play, and there is an "After you win..." event under the conclave ready to trigger, you can't trigger the agenda until the event is triggered

### ISSUE THREAD

**Issue by gil-wolbrum-hpe** [throneteki/throneteki#3460]
I had Marwen in play and "The Higher Mysteries" under the conclave and 3 gold
I won a challange with a maester, and now both the agenda and The Higher Mysteries are glowing as ready to trigger
(I want to trigger the conclave first to put a big char on top of the deck and then trigger The Higher Mysteries to put it in free)
But when I click the conclave it does not trigger only opens and closes the conclave window
Only after I triggered the event the game allowed me to trigger the agenda

 It looks like any "After you win..." event under the conclave will prevent the triggering of the agenda ability until the event is triggered

**Comment by Patane97** [comment]
Hey @gil-wolbrum-hpe; thanks for the report. This is already on our list to fix (https://github.com/throneteki/throneteki/issues/3179), and will likely be sometime soon considering there are a bunch of new _**Master**_ characters eventually coming out as part of the Mists of Memory cycle.

**Comment by Patane97** [comment]
Resolved in #3502
