### ISSUE TITLE
Decks can't be deleted + Very heavy bundle load

### ISSUE THREAD

**Issue by chris-torruella** [throneteki/throneteki#3517]
Since these new UI changes, I delete any deck and shows a banner of success but when reloading it is still there

I was trying to do this to alleviate the loading decks which currently blocks the site making very hard to impossible to load decks or play a game

**Comment by Patane97** [comment]
@chris-torruella this will be on our list of things to improve, although with testing this myself I noticed that the deck does get deleted, just after the "success" banner (took me around 5 seconds with 270ms ping). Will mark as an enhancement (closer to an improvement).

Hopefully you're seeing the same?

**Comment by chris-torruella** [comment]
It improved since the time I posted this, still there is a bit of an awkward long delay, then the banner is dismissed while the deck stays and after some more time it ends up disappearing
A small change I noticed also is how now in Decks, the first deck is not selected by default, so there is an empty state on the right

**Comment by Patane97** [comment]
Marking this as closed due to the dev updates to come (https://dev.throneteki.net). Deck lists are now paged for loading, _however_ there will still be a slight delay in saving & closing your deck (this is unavoidable with slow connections).
