### ISSUE TITLE
Auto-fill for deck creation doesn't work properly

### ISSUE THREAD

**Issue by chris-torruella** [throneteki/throneteki#3523]
When you edit a deck and try to add cards by typing to the list, there is some new auto-detection that fills up with the name of the cards, however this brings unintended issues. One example is trying to add any Valar plot as as soon you type "Val" adds the character Val to the list and doesn't let you do it (img attached)

Wondering whether this is needed at all as there was no problem with copy pasting and editing directly on the text area without assistance of any kind.

<img width="1052" alt="Screenshot 2024-08-01 at 10 43 30" src="https://github.com/user-attachments/assets/61cc5b23-83bb-4523-aee6-dea0a7b3a204">

**Comment by Patane97** [comment]
Will also mark this as closed, as the deck editor has been completely revamped for an upcoming release (view at https://dev.throneteki.net)
