### ISSUE TITLE
Iron throne account dont want to pair with Patreon account

### ISSUE THREAD

**Issue by Lobotom01** [throneteki/throneteki#3524]
Hi there,
im trying to link account on The Iron throne with Patreon and this is happend every time - 

![bug report](https://github.com/user-attachments/assets/a01e2fea-a928-4975-9b47-2a9b848758c3)

Im trying it almost a week and result is still the same.

Can You help me somehow :)

Thanks You and cheers!

Tomas

**Comment by Patane97** [comment]
@cryogen might be one for you to look into - will assign appropriately. :)
