### ISSUE TITLE
Queenscrown should always put the cards on the bottom of the deck

### ISSUE THREAD

**Issue by Chrisssie** [throneteki/throneteki#3526]
Hello team,

During a streamed match last night we found out the [Queenscrown](https://thronesdb.com/card/07019) should always place the cards on the bottom of the deck not just when there is a character in the 3 cards it finds. Also when a character is not chosen all cards should end up on the bottom.
Thank you in advance for fixing it :)! 
great work you all <3

Chris

**Comment by Patane97** [comment]
Fixed in https://github.com/throneteki/throneteki/pull/3541
