### ISSUE TITLE
Repeated errors

### ISSUE THREAD

**Issue by Omega-Eclipse** [throneteki/throneteki#3548]
Constantly seeing the error has occured page, even when I do not tab away.
I am running the latest version of firefox, I have all extensions disabled. Turning my VPN on and off does not help,I am running linux mint 20. I have tried deleting cookies and clearing the site cache. My firewall is configured apropriately and the only thing that I can seem to regularly do to cause it to error is open a video site like youtube.

**Comment by Patane97** [comment]
This should be resolved now after https://github.com/throneteki/throneteki/commit/d9dd7e4af8027f861e3b77e7782b724428e76496
