### ISSUE TITLE
prompt before saving a character using a duplicate

### ISSUE THREAD

**Issue by killerangel1863** [throneteki/throneteki#992]
Just wanted to put in a request for a prompt on whether or not a dupe is used to save a character. A relevant scenario would be if I have a duped Jorah with 2 betrayal tokens on him and I used Waking the Dragon to stand him during the challenge phase. At the end of the phase I actually want the Waking the Dragon to send him back to my hand. Thanks!

**Comment by zacchiro** [comment]
In fact, players will be prompted before using duplicates to save, but only if other options for saving a character exist (bodyguard, iron mines, etc.) This has been implemented by @ystros in #594 .
This request, which is totally valid, is hence something like "prompt before saving a character that can only be saved by a duplicate".

I agree it makes sense, and won't probably be much of a burden overall in terms of user experience.

If others thinks it would be, this is another good candidate for user-configuration options that would generalize what we already have for optional action windows.

**Comment by mplain** [comment]
It would be useful to have this implemented for situations where a duplicated character is controlled by another player (e.g. Warded) when it is being forced to leave play. Whether to save it or not is a legit question.
